### ISSUE TITLE
export file name without timeinput and timeout

### ISSUE THREAD

**Issue by tenadesign** [mifi/lossless-cut#321] opened 2020-04-21 08:20 UTC
1) i select different folder for output.  and i want exactly name input file name.
2) i want cut many videos but by turns. (only one video at a time, but automatic in order.)

how can I do?

**Comment by mattack1** [comment] 2020-04-21 21:43
Yeah, I really wish it had the same filename too.. *eventually* I guess I wish it would be able to replace the original file too.. i.e. replace in place.

**Comment by mifi** [comment] 2020-04-23 05:43
The problem is that if people do multiple cuts, then it will overwrite the previous cut.

**Comment by mifi** [comment] 2020-04-23 05:44
> 2. i want cut many videos but by turns. (only one video at a time, but automatic in order.)

You mean you want to do the same cut on multiple files? You could solve this by importing csv from the previous cut

**Comment by regagain** [comment] 2020-08-03 09:12
Hi! I came across Lossless Cut this morning and I really liked it. Actually I've been looking for something like that for a very long time.

It would be nice to have a setting to change the naming scheme. For example, I'd like the cut times to be replaced by the segment number.

**Comment by regagain** [comment] 2020-08-03 09:13
> The problem is that if people do multiple cuts, then it will overwrite the previous cut.

A dialog box warning the user when files are about to be overwritten would be nice.

**Comment by mifi** [comment] 2020-11-26 20:00
I'm closing this in favor of #96

**Closed by mifi** 2020-11-26 20:00 UTC
