### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mauretta2017** [mifi/lossless-cut#935] opened 2021-11-25 08:16 UTC
Please i recive this tex:
Unable to export this file
Try one of the following before exporting again:
Change output Format from MP4 to MOV
Select a different output Format (matroska and mp4 support most codecs)
Disable unnecessary Tracks
Try both Normal cut and Keyframe cut
Set a different Working directory
Try with a Different file
See Help
If nothing helps, you can send an Error report

Error: Command failed with exit code 1: D:\Users\mi16068\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\node_modules\ffmpeg-ffprobe-static\ffmpeg.exe -hide_banner -ss 845.33928 -i D:\Users\mi16068\Downloads\Tra Lerici e Turbia”(Purg. III, 49) “Tracce dantesche nel paesaggio vegetale ligure I Parte ore 14_00-16_00.mp4 -t 52.53569 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags +faststart -ignore_unknown -f mp4 -y D:\Users\mi16068\Desktop\video cut\Tra Lerici e Turbia”(Purg. III, 49) “Tracce dantesche nel paesaggio vegetale ligure I Parte ore 14_00-16_00-00.14.05.339-00.14.57.874-seg1.mp4
Impossibile trovare il percorso specificato.
    at makeError (D:\Users\mi16068\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (D:\Users\mi16068\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\app.asar\node_modules\execa\index.js:114:26)
    at async O (file:///D:/Users/mi16068/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:65013)
    at async file:///D:/Users/mi16068/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:65219
    at async file:///D:/Users/mi16068/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:192095

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "D:\\Users\\mi16068\\Downloads\\Tra Lerici e Turbia”(Purg. III, 49) “Tracce dantesche nel paesaggio vegetale ligure I Parte ore 14_00-16_00.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Baseline",
        "codec_type": "video",
        "codec_time_base": "13525089/637328000",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 0,
        "pix_fmt": "yuv420p",
        "level": 40,
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "2000/67",
        "avg_frame_rate": "318664000/13525089",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 608629005,
        "duration": "6762.544500",
        "bit_rate": "1296258",
        "bits_per_raw_sample": "8",
        "nb_frames": "159332",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "VSH264 stream handler"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/16000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "16000",
        "channels": 1,
        "channel_layout": "mono",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/16000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 108200960,
        "duration": "6762.560000",
        "bit_rate": "63957",
        "max_bit_rate": "63957",
        "nb_frames": "105665",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "handler_name": "AAC stream handler"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\Users\\mi16068\\Downloads\\Tra Lerici e Turbia”(Purg. III, 49) “Tracce dantesche nel paesaggio vegetale ligure I Parte ore 14_00-16_00.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 845.3392840515402,
        "end": 897.874975
      },
      {
        "start": 2192.406043,
        "end": 2208.142149
      },
      {
        "start": 3973.419933,
        "end": 4041.916694
      },
      {
        "start": 5747.155873,
        "end": 5861.023729
      },
      {
        "start": 6429.347623,
        "end": 6467.847827
      },
      {
        "start": 6558.842455,
        "end": 6589.34578
      },
      {
        "start": 6720.760032,
        "end": 6762.56
      }
    ],
    "fileFormatData": {
      "filename": "D:\\Users\\mi16068\\Downloads\\Tra Lerici e Turbia”(Purg. III, 49) “Tracce dantesche nel paesaggio vegetale ligure I Parte ore 14_00-16_00.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "6762.560000",
      "size": "1152646437",
      "bit_rate": "1363562",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf58.29.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.39.0"
}

**Comment by mifi** [comment] 2021-11-29 06:14
possible duplicate of #849
can you try the zip version of the github download instead? https://github.com/mifi/lossless-cut/releases/download/v3.39.0/LosslessCut-win.zip

**Comment by mifi** [comment] 2022-01-11 07:53
closing due to inactivity

**Closed by mifi** 2022-01-11 07:53 UTC
