### ISSUE TITLE
Release file handle when opening new file

### ISSUE THREAD

**Issue by cdalexndr** [mifi/lossless-cut#272] opened 2020-03-10 17:48 UTC
Open file, open new file, try to delete old file => file is till opened in LoselessCut

**Comment by mifi** [comment] 2020-03-19 15:53
I assume this is on windows, right?

**Comment by cdalexndr** [comment] 2020-03-19 18:13
Yes, Windows 10

**Comment by mifi** [comment] 2020-03-26 13:34
I just tested on Windows 8.1 and it works there.
1. drag drop a file from my desktop into losslesscut
2. drag drop another file from my desktop (choose open instead)
3. right click the first file on my desktop and delete it
4. success

Is this the same as you did?

**Comment by cdalexndr** [comment] 2020-04-03 12:34
Just reproduced with:

1. Open file
2. Select segments and export
3. File -> Close
4. App is still running
5. Try to delete old file

**Comment by cdalexndr** [comment] 2020-04-03 12:44
It seems it doesn't reproduce every time...

**Comment by cdalexndr** [comment] 2020-04-03 12:57
Reproduce it again with a ~3h video with 18 segments reduced to ~1h30m

**Comment by mifi** [comment] 2020-04-03 14:32
When delete gives an error, maybe you could check which process is holding the file open
Whether it is ffmpeg, ffprobe or LosslessCut itself.
https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows

**Comment by cdalexndr** [comment] 2020-04-03 21:44
**LosslessCut.exe** has the file handle blocking delete.

**Comment by mifi** [comment] 2020-04-11 07:30
I tried again now with the newest version and I'm still not able to reproduce this problem on Windows 8.1. I can even trash the file while it is open in LosslessCut. Could it be some stricter settings in your operating system configuration?

**Comment by cdalexndr** [comment] 2020-04-11 11:09
Forgot to mention version I'm using. You should add an Help -> About that displays version.
Version from right click -> Properties -> Details -> File version: **3.13.0.0**
I'll try newest version and report back if it's still a problem.

**Comment by cdalexndr** [comment] 2020-04-15 11:11
With 3.19.0, the file handle remains open in **ffprobe.exe**, but it gets released after some time.
I guess there is still pending work for ffprobe.

**Comment by cdalexndr** [comment] 2020-04-15 11:37
Also managed to reproduce stuck file handle in **LoselessCut** that doesn't get released.
Same as before, it doesn't reproduce every time.

**Comment by mifi** [comment] 2020-04-18 07:03
How long do you try to wait before checking the file handle? Does it get released after some time? I know that Windows has a lot of issue with file locking in general compared to MacOS/Linux which doesn't have a concept of locking files.

**Comment by cdalexndr** [comment] 2020-04-18 07:47
If it's locked by **ffprobe.exe** it gets released after some time (not much, ~1min).
If it's locked by **LoselessCut** it doesn't get released and I have to quit the program for the file handle to be released.

**Comment by mifi** [comment] 2020-04-18 07:51
Ok. Do you see any other patterns? Like did it ever happen from just opening a file and then closing it? Or do you have to cut first for this to happen? Does it happen  with only some file types?

**Comment by cdalexndr** [comment] 2020-04-18 08:04
I always cut the file then try to delete old one (the source).
Only used it on **mkv** files.
Some files that are online stream recordings may have empty/invalid time frames where the streaming hanged and resumed later.

**Comment by cdalexndr** [comment] 2020-05-20 11:54
Just reproduced file handle stuck temporary by **ffprobe.exe** and also permanently by **LoselessCut 3.19.0** with:
1. Open file
2. Browse timeline
3. File -> Close
4. Cannot delete file

So the editing has nothing to do with file handle getting stuck.
Files are .mkv, 2-3 GB size.

**Comment by MisterReally** [comment] 2021-10-12 23:40
I am experiencing the same issue consistently.  

Windows 10 Enterprise 
LosslessCut 3.39.0 (Built locally - not installed from Windows Store)

Clicking the trash icon after editing file of size 433,373 KB displays the following messages in 'Developer Tools' view (I replaced some file path values with a string enclosed with <> for privacy):

react_devtools_backend.js:4049 
react_devtools_backend.js:4049 
trashResponse 
{tmpFiles: true, projectFile: true, sourceFile: true}

Command failed: C:\Users\<acsii_string>\AppData\Local\Temp\7dd5c8b8-fe4c-41ff-bda7-7f7313e0caad.tmp.exe D:\<ascii_string>\<ascii_string> 2021-10-12 15_04-cap.mp4

    at ChildProcess.exithandler (child_process.js:308)
    at ChildProcess.emit (events.js:210)
    at maybeClose (internal/child_process.js:1021)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283)

A dialog appears with message:  "Unable to move file to trash.  Do you want to permanently delete it? 

User then selects button labeled "Permanently delete" and receives the following exceptions:

Error: ENOENT: no such file or directory, unlink ' D:\<ascii_string>\<ascii_string> 2021-10-12 15_04-cap-proj.llc'
overrideMethod	@	react_devtools_backend.js:4049
Promise.catch (async)		
(anonymous)	@	main.36c952cf.chunk.js:1
async function (async)		
(anonymous)	@	main.36c952cf.chunk.js:1
Ve	@	2.02f77fbb.chunk.js:2
Ke	@	2.02f77fbb.chunk.js:2
(anonymous)	@	2.02f77fbb.chunk.js:2
Cr	@	2.02f77fbb.chunk.js:2
wr	@	2.02f77fbb.chunk.js:2
(anonymous)	@	2.02f77fbb.chunk.js:2
Le	@	2.02f77fbb.chunk.js:2
(anonymous)	@	2.02f77fbb.chunk.js:2
Ir	@	2.02f77fbb.chunk.js:2
Jt	@	2.02f77fbb.chunk.js:2
Zt	@	2.02f77fbb.chunk.js:2
t.unstable_runWithPriority	@	2.02f77fbb.chunk.js:2
Vi	@	2.02f77fbb.chunk.js:2
Pe	@	2.02f77fbb.chunk.js:2
Qt	@	2.02f77fbb.chunk.js:2

react_devtools_backend.js:4049 Error: EBUSY: resource busy or locked, unlink ' D:\<ascii_string>\<ascii_string> 2021-10-12 15_04-cap.mp4'
overrideMethod	@	react_devtools_backend.js:4049
(anonymous)	@	main.36c952cf.chunk.js:1
async function (async)		
(anonymous)	@	main.36c952cf.chunk.js:1
Ve	@	2.02f77fbb.chunk.js:2
Ke	@	2.02f77fbb.chunk.js:2
(anonymous)	@	2.02f77fbb.chunk.js:2
Cr	@	2.02f77fbb.chunk.js:2
wr	@	2.02f77fbb.chunk.js:2
(anonymous)	@	2.02f77fbb.chunk.js:2
Le	@	2.02f77fbb.chunk.js:2
(anonymous)	@	2.02f77fbb.chunk.js:2
Ir	@	2.02f77fbb.chunk.js:2
Jt	@	2.02f77fbb.chunk.js:2
Zt	@	2.02f77fbb.chunk.js:2
t.unstable_runWithPriority	@	2.02f77fbb.chunk.js:2
Vi	@	2.02f77fbb.chunk.js:2
Pe	@	2.02f77fbb.chunk.js:2
Qt	@	2.02f77fbb.chunk.js:2

**Comment by mifi** [comment] 2021-11-03 05:17
I think it may be related to this chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=969049

i suspect that it happens when first opening a natively supported file (which creates a <video> tag. Then if later opening a not natively supported file the <video> tag is automatically removed by React but the video is still open in chromium due to that bug. It may have been fixed in newest chromium/electron, but we are being held back from upgrading electron due to macos issues #7140

**Comment by aCuria** [comment] 2022-02-25 15:34
Same issue with Windows 11, Lossles Cut v3.4.3

"Trash Can" function also does not work

**Comment by mifi** [comment] 2022-02-25 17:05
@aCuria do you see which program is locking the file? Is it losslesscut.exe or is it ffprobe.exe ? and if you wait for a few minutes, will it resolve?

**Comment by mifi** [comment] 2022-02-26 07:22
I did some improvements to the Canvas player (unsupported files player) that will hopefully resolve this in the next version

**Comment by mifi** [comment] 2022-03-13 04:32
Would be nice to see whether the newest version has improved this situation

**Comment by aCuria** [comment] 2022-03-17 20:39
No change in v3.44...

The bug seems to be related to not closing the original file after proxy generation

**Comment by mifi** [comment] 2022-03-18 05:23
Is it still LosslessCut.exe holding the file handle, or is it ffmpeg.exe or ffprobe.exe?

**Comment by aCuria** [comment] 2022-03-29 03:13
Yes, LosslessCut is holding the file handle according to windows.

**Comment by mifi** [comment] 2022-03-29 04:06
Thank you. Then I honestly don’t know what’s causing it but hopefully after upgrading Electron to the latest version it will be solved.

**Comment by mikeyaworski** [comment] 2022-05-18 07:23
I've been using release 3.44.0 and still run into this issue. The way I find myself running into it either exporting + deleting videos in a large batch, or exporting videos that are large in size. My typical workflow might be:

Large batch:
- Open a batch of 20-40 files
- Go through each one, export a portion of it, then delete it
- At some point, deleting one of them will fail

Large videos:
- Exporting part of a movie (mp4 or mkv) and then deleting

It seems extra likely for deleting to fail if you leave lossless cut open in the background for a while, and then come back to it. This may or may not be true.

**Comment by mifi** [comment] 2022-05-21 19:29
What's useful to observe in order for me to fix this:
1. Is it LosslessCut.exe, ffprobe.exe or ffmpeg.exe is holding the file?
2. Does the file get released/unlocked after a few minutes?

If 2 is true, it might be possible to workaround this issue by having losslesscut continuously retrying to delete the file in a while-try-catch loop for a few minutes after the delete button is pressed, to remedy these issues on windows.

**Comment by mikeyaworski** [comment] 2022-05-22 00:08
1. The Windows prompt says LosslessCut. I'll look closely next time it happens and update this thread.
2. I don't believe so. I've been working my way through 40 files in a batch before, where one of the first gets locked, and even once I've gone through the rest of the batch, the first is still locked. I'll do a test for this the next time it happens though.

**Comment by mifi** [comment] 2022-05-22 04:48
If it never gets released and it's LosslessCut.exe that's holding the file handle (and you see no ffmpeg.exe or ffprobe.exe processes in Task Manager), then that's probably an electron bug and may be fixed once we upgrade electron to the newest version #714

**Comment by mikeyaworski** [comment] 2022-05-28 04:34
Writing to confirm that there are no ffmpeg or ffprobe processes in task manager, and it never gets released.

And for clarification, I try to delete the file from within LosslessCut (the `d` shortcut), and it says it's unable to move the file to trash. I then try to delete it with the Windows File Explorer and it says "The action can't be completed because the file is open in LosslessCut"

**Comment by mifi** [comment] 2022-05-28 21:17
Even after opening a new file, llc still holds the handle to the old file indefinitely? I hope this will be fixed when we upgrade electron

**Comment by mikeyaworski** [comment] 2022-05-28 23:43
Yes it does. I need to close LosslessCut before I'm able to delete the file.

**Comment by mifi** [comment] 2022-06-04 03:32
Update: seems to be a problem also on MacOS, although less visible #1179

**Comment by fade0ff** [comment] 2022-09-08 18:36
I have a similar problem in Win10 and version 3.46.2 . After exporting a cut version with embedded JPEG, and closing the file with Ctrl+W (or File->Close) I'm regularly unable to delete the original file unless I close LosslessCut. I if use ResMon or Process Explorer to search for the blocking handler, both report LosslessCut.exe _twice_ (!).
These locks also don't disappear after some minutes. The only way to delete the file is to close LosslessCut.
Locks pretty much like the input file handle is not released properly.
This seems to be only a problem for bigger files though. I.e. I can't really reproduce this issue for smallish MP4s, but for those close to 1GB, it seems to happen absolutely every time.

**Comment by mifi** [comment] 2022-11-23 09:41
If you can try again with the newest version that'd be great. now upgraded to electron 21.

**Comment by fade0ff** [comment] 2022-11-23 17:14
I tried some larger files with 3.48.2 beta and closing them with Ctrl-W after exporting seems to release the file handle immediately and I can e.g. delete the original file -> seems to work for me. Thanks!

**Comment by mifi** [comment] 2022-11-24 01:51
great! I'll close this and we can reopen if it's still a problem

**Closed by mifi** 2022-11-24 01:51 UTC
Labels: bug, Cannot reproduce
