### ISSUE TITLE
Can't hear Opus Audio when trimming

### ISSUE THREAD

**Issue by ele3131** [mifi/lossless-cut#1681] opened 2023-08-15 22:14 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Downloaded a YouTube video (Mkv with Opus Codec) and it does not read the sound, only version 3.39.0 and down does.

### Expected behavior

Hearing the audio track as 3.39.0

### Actual behavior

Audio track does not play.

**Comment by mifi** [comment] 2023-08-17 14:15
could you provide link to the youtube video?

**Comment by ele3131** [comment] 2023-08-20 22:51
> could you provide link to the youtube video?

https://www.youtube.com/watch?v=pSys1DkRIHg

I believe any YouTube video downloaded as .mkv will reproduce the issue (all of them contain Opus audio).

**Comment by mifi** [comment] 2023-08-20 23:03
I used this command:
```
yt-dlp -f 600 https://www.youtube.com/watch?v=pSys1DkRIHg
```

```
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
600 webm  audio only      2 │  896.11KiB  35k https │ audio only         opus        35k 48k [pt] ultralow, webm_dash
```

and i can hear audio when i import it into losslesscut and play back. not sure how to reproduce this problem...

**Comment by ele3131** [comment] 2023-08-20 23:21
> I used this command:
> 
> ```
> yt-dlp -f 600 https://www.youtube.com/watch?v=pSys1DkRIHg
> ```
> 
> ```
> ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
> ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 600 webm  audio only      2 │  896.11KiB  35k https │ audio only         opus        35k 48k [pt] ultralow, webm_dash
> ```
> 
> and i can hear audio when i import it into losslesscut and play back. not sure how to reproduce this problem...

[my ordinary life - the living tombstone (sped up nightcore).zip](https://github.com/mifi/lossless-cut/files/12389382/my.ordinary.life.-.the.living.tombstone.sped.up.nightcore.zip)

Gives me an error message that "File without Native Support" (translated), however older versions as 3.39.0 works fine.

**Comment by mifi** [comment] 2023-08-21 09:40
hmm it works for me. im on macos. did you try on a different computer?

**Comment by ele3131** [comment] 2023-08-30 00:35
> hmm it works for me. im on macos. did you try on a different computer?

On Windows 10 is plays but without Audio, and on Windows 11 it gives "File Not Supported".

**Comment by mifi** [comment] 2023-09-05 21:36
I don't know where the message "file not supported" comes from. Afaik LosslessCut source code doesn't contain that message anywhere. I honestly don't know how to solve this, as it seems to be platform-dependent.

**Comment by mifi** [comment] 2023-12-30 10:18
unfortunately nothing actionable for me here, closing

**Closed by mifi** 2023-12-30 10:18 UTC
