### ISSUE TITLE
Arm64 Jammy does not properly show roll down menus .

### ISSUE THREAD

**Issue by v8karlo** [mifi/lossless-cut#1281] opened 2022-08-25 23:45 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Recently I switched to Arm64 Ubuntu Jammy and roll down menus are empty , some of them .
LossLessCut is working perfectly with drag and drop , but can not open file through drop down menu .
Could be because new Jammy does not use GTK but Gnome controls , could be , not sure .

Probably is needed to compile on Jammy and everything will be ok again .

Can you compile Arm64 version on Jammy to correct this small error .
Jammy is next long term linux distro and most of users will use that linux .

Some of the menus contains controls , like HELP , and are working fine .

#

![image](https://user-images.githubusercontent.com/57914925/186787259-e8bc28b9-c9c9-4b1b-add5-305635dcd7e1.png)

#

![image](https://user-images.githubusercontent.com/57914925/186787329-7831af73-d047-424d-abcb-568333d04edd.png)

#

![image](https://user-images.githubusercontent.com/57914925/186787372-36bf96f4-98c1-4015-b458-ba2f3673e306.png)

#

![image](https://user-images.githubusercontent.com/57914925/186787422-e531345f-3479-46ec-9a66-2099c5233baf.png)

#

![image](https://user-images.githubusercontent.com/57914925/186787453-94762c35-1962-4e58-a524-2638279245c2.png)

#

![image](https://user-images.githubusercontent.com/57914925/186787484-86869c20-335e-4292-9b71-588cfdf02e94.png)

#

lossLessCut is one of a kind on Linux and Android 
and was accepted on Arm64 excellently !

Thank you in advance , you are the best !

**Comment by v8karlo** [comment] 2022-08-31 19:58
#

Arm64 Ubuntu Jammy Nordic

#

![image](https://user-images.githubusercontent.com/57914925/187770796-0590699c-2596-476f-8d5b-2730e0c02ef0.png)

#

**Comment by mifi** [comment] 2022-09-01 22:37
I'm tninking maybe it's caused by the old electron version used by losslesscut. hopefully will be fixed once we upgrade #714

**Comment by v8karlo** [comment] 2022-09-02 02:11
When you made Arm64 version there was a lots of interest in LossLessCut .

Users started to install Ubuntu proot on mobiles just to be able t use LossLessCut .

Thank you !

**Comment by defencedog** [comment] 2022-09-03 19:49
@v8karlo  @mifi 
I have faced this issue using `xfce` on Galaxy Tab 7 
Solution: Change theme to _**-hidpi_ or _**.xdpi_
or
Settings Manager > Appearance > Settings > Window Scaling and select 2 as the scaling factor

**Comment by v8karlo** [comment] 2022-09-04 18:21
No, I just tried hidpi and scalling . Same .
But app is working fine via drag & drop , so issue is not big .
And Yiffy suspect that is the old version of electron , which could be .

Thanks anyway !

**Comment by pecbraz** [comment] 2022-09-12 15:18
I'm having the same issue. In my case, the menus Edit and Tools work, but not the others

**Comment by mifi** [comment] 2022-11-23 09:41
if you can test with the newest version now ([3.48.2](https://github.com/mifi/lossless-cut/releases/tag/v3.48.2)), maybe it's fixed

**Comment by pecbraz** [comment] 2022-12-21 12:28
I confirm the issue is fixed with version 3.48.2 beta

Thanks!

**Closed** 2022-12-22 15:38 UTC
