### ISSUE TITLE
Unable to merge files with certain names?

### ISSUE THREAD

**Issue by jonas1015119** [mifi/lossless-cut#910] opened 2021-10-31 21:40 UTC
Files with the name scheme "XXX..._XX.file" export fine, but get an error when merging. I renamed another file in the same manner and it reproduced the error.

" Impossible to open '_123-00.00.00.000-00.02.11.517-seg1.mov'
pipe:: No such file or directory"

the full file name was "20211030..._123.mov", so for some reason multiple dots cause it to ignore the first half of the file name which then results in it not being able to find the correct file.

**Comment by mifi** [comment] 2021-11-15 06:31
That's odd. I tried output template with `...` in it and it works for me. Which OS are you on?

possibly related #889

**Comment by mifi** [comment] 2021-11-15 16:43
Ah. I managed to reproduce the problem now on MacOS too. It's an issue with ffmpeg. I can confirm that this issue has been solved by this commit https://github.com/mifi/lossless-cut/commit/833ab45c587ade65329de5d3d4298f3653a24630

Fix will be included in the next release. Closing this, thanks for reporting!

**Closed by mifi** 2021-11-15 16:43 UTC
