### ISSUE TITLE
export+merge does not cut at exact same point while using I and O (cut start and cut end)

### ISSUE THREAD

**Issue by mxav1111** [mifi/lossless-cut#959] opened 2021-12-27 04:57 UTC
This is standard MP4 file.
While removing some part of mp4 file (using I and O to set the start and end markers) , it needs to also cut into the additional track to ensure subtitle track remains in sync. Currently it is going out of sync when clip is cut out since it is only cutting the movie part. Audio track is in proper sync but not the subtitle track.
Thanks for looking and trying to resolve this.

**Comment by mifi** [comment] 2022-01-01 08:18
any more info about the file or subtitle track? could you provide a report from the app or a sample file?

do you add the subtitle track from another file or is it inside the main mp4 file?

possibly a duplicate of #955

**Comment by mxav1111** [comment] 2022-01-01 19:04
Thanks for the response.
It is inside mp4 file track.
It actually happens to any mp4 with subtitle track.

My use case is
1. Record a movie or a show (using playon)
2. Cut out some clips (using losslesscut) that would be somewhat
incompatible to watch in family with grand parents, preteen and teen
children together.
3. Sit down together for family watch.
4. Use vlc (laptop connected to hdmi TV)
5. After every cut point arrival during watching go into vlc main menu -
tools - track synchronization - subtitles track -  put negative  value to
hasten the display of subtitles instead of positive value to delay subtitle
display.
6. One more point.  Problem is actually may not be easy to detect or so
probably because I have to put only small like 2 3 seconds of haste to
display when I am cutting clip for 5 10 seconds. So there's a problem but
it is not delaying display of subtitle exactly how much seconds of video on
screen is being cut but rather less small haste (negative value in vlc)
every time with increasing value manually after crossing each cut point in
vlc to maintain sync.
So yes it is delaying display of subtitles if scenes are cut for sure.  May
be somewhere very small mathematical error or subtraction issue likely.

Hope this helps. If you would like QA please let me know or a group channel
or something I can join , it would be pleasure to assist.

Another off topic point. I haven't created enhancement request yet with
something similar will be very nice.

So... if there's a way to directly allow edit while viewing channel video
it would be awesome and then losslesscut created file can be read by
compatible player and automatically skip those cut points.  Just some
thoughts as I think lots of family people living together with  grand
parents and children would like to have this as single solution preferably
in public domain and we can share these  lossesscut created  text files
with cut point markers and people can then again edit further if they
prefer so. Or maybe losslesscut can change cut point file format to same
cut points that usually are utilized in marking advertises.

Thanks for your help.

Max.

**Comment by mxav1111** [comment] 2022-01-01 19:23
One more point.
You might want to consider burn-in subtitles (overlay or map of ffmpeg) in
output if that helps in proper sync. It will definitely work in my case as
personally we always play movies with subtitles on (this has helped
children improve literacy in our case and some sci-fi movies are just
impossible to understand without subtitles)
But yes others might not like but if this helps in subtitles sync and if
possible this can always be given as option somewhere in settings or so.
Just some thoughts.

**Comment by mxav1111** [comment] 2022-01-03 04:06
There's another problem reported on reddit  with subtitles when recorded
from channel with ads.

https://www.reddit.com/r/PlayOn/comments/rtkoiw/playon_and_subtitles/?utm_medium=android_app&utm_source=share

**Comment by mifi** [comment] 2022-01-05 09:55
Unfortunately there's not much actionable for me to do. If you can share a file and instructions on how to reproduce the problem, then

> So... if there's a way to directly allow edit while viewing channel video it would be awesome and then losslesscut created file can be read by compatible player and automatically skip those cut points. Just some thoughts as I think lots of family people living together with grand parents and children would like to have this as single solution preferably in public domain and we can share these lossesscut created text files with cut point markers and people can then again edit further if they prefer so. Or maybe losslesscut can change cut point file format to same cut points that usually are utilized in marking advertises.

I'm not sure if you're talking about editing a live video stream on-the-fly. If so, then that's not something losslesscut will probably ever support. If you want to import cutpoints exported from another software, this can already be done with support for many different formats. If you're looking to support a particular new format, then please provide an example file and I can implement support.


> You might want to consider burn-in subtitles (overlay or map of ffmpeg) in

burn-in is not lossless, but see #372

**Comment by mifi** [comment] 2022-07-25 10:07
closing due to lack of response

**Closed by mifi** 2022-07-25 10:07 UTC
