### ISSUE TITLE
Wrong information (metadata) in output file

### ISSUE THREAD

**Issue by passat1** [mifi/lossless-cut#123] opened 2019-02-08 12:36 UTC
After cutting part (00.00.00.000-00.13.49.296) of input MKV file with MediaInfo:
~~~
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 2 h 14 min
Bit rate                                 : 3 630 kb/s
Width                                    : 1 920 pixels
Height                                   : 804 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.098
Stream size                              : 3.41 GiB (94%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 2 h 14 min
Bit rate                                 : 238 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 229 MiB (6%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : en:Chapter 01
00:03:48.729                             : en:Chapter 02
00:07:45.465                             : en:Chapter 03
00:11:16.593                             : en:Chapter 04
00:17:41.811                             : en:Chapter 05
00:21:03.179                             : en:Chapter 06
00:27:24.184                             : en:Chapter 07
00:33:34.846                             : en:Chapter 08
00:37:22.282                             : en:Chapter 09
00:45:24.013                             : en:Chapter 10
00:52:19.595                             : en:Chapter 11
00:56:57.205                             : en:Chapter 12
01:03:11.413                             : en:Chapter 13
01:10:44.991                             : en:Chapter 14
01:15:25.730                             : en:Chapter 15
01:21:45.943                             : en:Chapter 16
01:26:59.172                             : en:Chapter 17
01:32:18.199                             : en:Chapter 18
01:36:43.923                             : en:Chapter 19
01:43:25.574                             : en:Chapter 20
01:50:23.283                             : en:Chapter 21
01:54:22.898                             : en:Chapter 22
02:00:41.109                             : en:Chapter 23
02:07:53.332                             : en:End Credits
~~~~
Output file MediaInfo:
~~~
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 13 min 49 s
Bit rate                                 : 3 630 kb/s
Width                                    : 1 920 pixels
Height                                   : 804 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Variable
Frame rate                               : 233.510 FPS
Original frame rate                      : 23.976 (24000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.010
Stream size                              : 3.41 GiB
Default                                  : Yes
Forced                                   : No
Color range                              : Limited

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 13 min 49 s
Bit rate                                 : 238 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 229 MiB (61%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : :Chapter 01
00:03:48.729                             : :Chapter 02
00:07:45.465                             : :Chapter 03
00:11:16.593                             : :Chapter 04
~~~~
When this (output) file is re-muxed with MKVToolnix, MediaInfo looks like this (correct):
~~~
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 13 min 49 s
Bit rate                                 : 3 529 kb/s
Width                                    : 1 920 pixels
Height                                   : 804 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.095
Stream size                              : 349 MiB (93%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 13 min 49 s
Bit rate                                 : 248 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 24.5 MiB (7%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : :Chapter 01
00:03:48.729                             : :Chapter 02
00:07:45.465                             : :Chapter 03
00:11:16.593                             : :Chapter 04
~~~~

In output file some info is just copied from input file, like this:
~~~
Video
Bit rate                                 : 3 630 kb/s
Stream size                              : 3.41 GiB

Audio
Bit rate                                 : 238 kb/s
Stream size                              : 229 MiB
~~~
and some are nonsense, like this:
~~~
Frame rate                               : 233.510 FPS
Bits/(Pixel*Frame)                       : 0.010
~~~
Probably instead of **output file** total frame number, for calculation is used **input file** total frame number

**Comment by mifi** [comment] 2019-02-08 15:41
Is it the same problem if you run manually from the command line: `ffmpeg -ss 10 -i INPUT.mkv -t 15 -c copy OUTPUT.mkv` ?

**Comment by passat1** [comment] 2019-02-08 20:14
MediaInfo of file created with ffmpeg fron program installation as you suggested:
~~~
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 25 s 24 ms
Bit rate                                 : 3 630 kb/s
Width                                    : 1 920 pixels
Height                                   : 804 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Variable
Frame rate                               : 7 738.811 FPS
Original frame rate                      : 23.976 (24000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.000
Stream size                              : 3.41 GiB
Default                                  : Yes
Forced                                   : No
Color range                              : Limited

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 25 s 2 ms
Bit rate                                 : 238 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 229 MiB
Language                                 : English
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : :Chapter 01
~~~
Yes.
That is problem with ffmpeg.
I repeated same operation with "ffmpeg-4.1-win64-static" and result is same again.

**Comment by mifi** [comment] 2019-02-08 20:15
Could try try to run the command `ffmpeg -i INPUT.mkv -c copy OUTPUT.mkv` (without any cut)?

**Comment by passat1** [comment] 2019-02-08 20:17
I will do that and edit this post when done.

**Comment by passat1** [comment] 2019-02-08 20:41
But when input file is MP4 (different file), then output (cut) to MKV looks like this:
~~~
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 25 s 25 ms
Width                                    : 1 280 pixels
Height                                   : 544 pixels
Display aspect ratio                     : 2.35:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Default                                  : Yes
Forced                                   : No
Color range                              : Limited

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 25 s 2 ms
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : :Last Chance (Credits)
~~~
and output to MP4:
~~~
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 25 s 25 ms
Bit rate                                 : 7 186 kb/s
Width                                    : 1 280 pixels
Height                                   : 544 pixels
Display aspect ratio                     : 2.35:1
Frame rate mode                          : Variable
Frame rate                               : 23.976 (24000/1001) FPS
Minimum frame rate                       : 23.974 FPS
Maximum frame rate                       : 23.981 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.430
Stream size                              : 21.4 MiB (98%)
Color range                              : Limited
Menus                                    : 3
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 25 s 3 ms
Bit rate mode                            : Variable
Bit rate                                 : 153 kb/s
Maximum bit rate                         : 185 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 466 KiB (2%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Menus                                    : 3

Menu #1
ID                                       : 3
Codec ID                                 : text
Duration                                 : 15 s 0 ms
Language                                 : English
Menu For                                 : 1,2
00:00:00.000                             : Last Chance (Credits)
~~~

Did not find any errors, beside false variable video frame rate in MP4 file, which is well known issue.

**Comment by mifi** [comment] 2019-02-10 14:07
So this is an issue with files that have variable frame rate? Maybe you can file a bug at ffmpeg with a reproducable case?

**Comment by passat1** [comment] 2019-02-10 19:00
Input files do not have variable frame rate but ffmpeg output MP4 files have info as they have variable frame rate, but that is false info.
It is visible in MediaInfo of MP4:
~~~
Frame rate mode                          : Variable
Frame rate                               : 23.976 (24000/1001) FPS
Minimum frame rate                       : 23.974 FPS
Maximum frame rate                       : 23.981 FPS
~~~
Output from same file to MKV:
~~~
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
~~~
That is nothing important and not new. It is well known fact.

**Comment by mifi** [comment] 2022-02-12 09:49
Not much I can do about this because it's ffmpeg. Hopefully will be solved in the future. Closing this, thanks!

**Closed by mifi** 2022-02-12 09:49 UTC
Labels: bug, ffmpeg
