### ISSUE TITLE
Audio from M2TS

### ISSUE THREAD

**Issue by VERSEAU44** [mifi/lossless-cut#668] opened 2021-02-18 16:59 UTC
Hi !

The 3.31.1 and 3.32.0 versions do not keep aufio from M2TS file

The 3.20.1works fine for this ...

Thkanks to resolve the trouble ...
Laurent

**Comment by mifi** [comment] 2021-02-18 17:56
Hi

I just tried with an m2ts file and it works for me, audio is still there. can you provide an example file?

**Comment by VERSEAU44** [comment] 2021-02-21 11:10
Hi

On [https://we.tl/t-honQx8qj06](url), I extracted 5s from a same m2ts video :
. with 3.20.1 version : the export was done the first time and VLC reads the sound without problem (CTRL + J shows all the audio streams)
. with 3.31.1 version : the export does not work the first time. I had to remove the subtitles. CTRL + J in VLC shows that there is no audio stream
. with 3.32.0 version : same as 3.31.1 version

Thanks for your help
Laurent

**Comment by mifi** [comment] 2021-02-21 16:34
Thanks for submitting a sample. I can also reproduce the problem.
It seems to not be related to LosslessCut, but the version of ffmpeg included in losslesscut.
- Current losslesscut uses ffmpeg  4.3.3
- llc 3.20.1 uses ffmpeg 4.2.2.

I have a simple command to reporduce the problem:
```bash
ffmpeg -hide_banner -ss '2.48000' -i 3.20.1.m2ts -c copy -map '0:0' -map '0:1' -y out.m2ts
```

When I try to cut with version 4.2.2 from the command line, the sound is still there, but 4.3.3 no sound.

I can see that ffmpeg 4.2.2 is spewing out some error:

```
[aac @ 0x7fa55f00e400] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7fa55f00e400] decode_pce: Input buffer exhausted before END element found
[aac @ 0x7fa55f00e400] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7fa55f00e400] Reserved bit set.
[aac @ 0x7fa55f00e400] Prediction is not allowed in AAC-LC.
[aac @ 0x7fa55f00e400] Reserved bit set.
[aac @ 0x7fa55f00e400] Number of bands (21) exceeds limit (4).
[aac @ 0x7fa55f00f000] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7fa55f00f000] Inconsistent channel configuration.
[aac @ 0x7fa55f00f000] get_buffer() failed
Input #0, mpegts, from '3.20.1.m2ts':
  Duration: 00:00:06.41, start: 1.400000, bitrate: 4492 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(top first), 1440x1080 [SAR 4:3 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x101](fra): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 131 kb/s
    Stream #0:2[0x102](qad): Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 62 kb/s
    Stream #0:3[0x103](qaa): Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 65 kb/s
    Stream #0:4[0x104](fre,fre,fre): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
Output #0, mpegts, to 'out.m2ts':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(top first), 1440x1080 [SAR 4:3 DAR 16:9], q=2-31, 25 fps, 50 tbr, 90k tbn, 90k tbc
    Stream #0:1(fra): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 131 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   95 fps=0.0 q=-1.0 Lsize=    2259kB time=00:00:03.85 bitrate=4799.2kbits/s speed= 845x    
video:1972kB audio:67kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 10.824157%
```

4.3.3 the same errors, but also this line:

```
[mpegts @ 0x7fdf50014000] Stream 1, codec aac, is muxed as a private data stream and may not be recognized upon reading.
```
But I'm not sure if it's related to the issue.

There's not much I can do about this issue in LosslessCut. Either something is wrong with your file or (more likely) ffmpeg has a bug.
It could be reported to ffmpeg.

**Comment by mifi** [comment] 2023-12-30 10:59
I've created a new overview issue for MPEG TS related problems: https://github.com/mifi/lossless-cut/issues/1839 - I will close this issue because there isn't any obvious actionable solution.

**Closed by mifi** 2023-12-30 10:59 UTC
Labels: bug, ffmpeg
