### ISSUE TITLE
Add a keyboard action to copy last run ffmpeg commands to clipboard

### ISSUE THREAD

**Issue by YousufSSyed** [mifi/lossless-cut#1529] opened 2023-03-30 08:00 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Right now you can see previous FFmpeg commands on LosslessCut. However I don't want to make lossless cuts, I want to make lossy cuts with my own commands, this functionality won't be added to Losslesscut for a long time if ever. I'd like to see and copy the command after I make a clip and without hitting export, so I could edit that and run it in my terminal to create my clip. 

Perhaps a button should be added next to "Export" called "Preview Command" to see the command, like you can see previous FFmpeg commands. I also think a hotkey should be added to copy what the command would be if you pressed export, without clicking any buttons on the screen.

**Comment by mifi** [comment] 2023-04-03 02:26
the problem is that it's not just one command that will be run when your press export. it's a multitude of different commands, and some depend on the result of the previous commands. I think it's going to complicate the code unnecessarily if I were to implement this. So unfortunately I don't think this will be implemented.

Kind of related: #750 #980

**Comment by YousufSSyed** [comment] 2023-04-03 02:28
@mifi How about copying all the commands to the clipboard?

**Comment by mifi** [comment] 2023-04-03 02:54
I think the «last ffmpeg commands» page should serve this purpose. You can even bind a keyboard shortcut to open it. Maybe it could be improved with a button though that would allow you to copy the last commands. Or maybe a keyboard shortcut to copy the last run commands to clipboard.

**Comment by YousufSSyed** [comment] 2023-04-03 02:56
Why did you change the title?! 
I don't want the extra step of exporting the video, why don't I just get what would be the "last ffmpeg command" without having to make the video first?

**Comment by mifi** [comment] 2023-04-03 02:59
Ok feel free to change the title back, but like I said it’s not feasible to implement «last commands only» like you asked, so I thought this could be a middle-way. But then I’ll have to close this issue again.

**Closed by mifi** 2023-04-03 02:59 UTC
Labels: enhancement

**Comment by YousufSSyed** [comment] 2023-04-03 03:00
@mifi Maybe I should clarify, when losslesscut exports a video, a command shows up in "last ffmpeg commands." I want the command before exporting the video of what that command would be. 

So you're saying that its not feasible to add? If so, can you elaborate?

**Comment by mifi** [comment] 2023-04-03 03:25
The problem is that when you press export:
- losslesscut will generate one of many possible ffmpeg commands, depending on options
- Then it will run this command
- Then it will generate a new ffmpeg command, but this command’s arguments **depends on the result of finishing running the first ffmpeg command**
- then it will run this new command
- And so on…
- Once finished running all the commands, losslesscut will collect them and put them on the «last ffmpeg commands» page

So my point is that before exporting any videos, the commands are not yet known and cannot be shown to the user

**Comment by YousufSSyed** [comment] 2023-04-03 04:56
@mifi So a dry run wouldn't be possible?

**Comment by mifi** [comment] 2023-04-03 11:49
not in the current state at least

**Comment by YousufSSyed** [comment] 2023-04-04 03:27
Fine I'll leave it that. I opened another feature request to try to do what I want: [A menu option and or shortcut to quickly copy the start end end times of the current segment to the clipboard](https://github.com/mifi/lossless-cut/issues/1535).
