### ISSUE TITLE
Program didn't detect right OS language

### ISSUE THREAD

**Issue by bovirus** [mifi/lossless-cut#1500] opened 2023-03-06 08:33 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 11

### Steps to reproduce

My configuration is Windows 11 22H2 64bit with Italian language

With LoseLessCut default configuration language (System language) LoseLessCut start in English (didn't detect Italian OS).

If I set language as Italian it show GUI in Italian.

If in LoselessCut with Italian GUI I set "Lingua sistema" (System language in italian) it switch in English (detect system as English instead as Italian).

### Expected behavior

In my configuration with default system setup language should start in Italian.

### Actual behavior

Start in english instead in Italian

**Comment by bovirus** [comment] 2023-03-08 16:19
@mifi 

No news?

Thanks. KR.

**Comment by mifi** [comment] 2023-03-09 09:50
Duplicate of #1366

**Closed by mifi** 2023-03-09 09:50 UTC

**Comment by bovirus** [comment] 2023-03-09 10:00
@mifi 

Could you please enable at least the detection of some language (like italian) that are fully support?

For me and italian user is a big benfit.

Thanks.

**Comment by mifi** [comment] 2023-03-09 10:38
I could do that but my concern is that someone might sabotage the translation for Italian (or any other language). I cannot verify whether the translations valid in the future, because I don’t have any trusted person controlling the translations. Unless it’s possible to lock down a langauge in weblate and give only edit access to a specific person, but i dont know if that’s possible.

**Comment by bovirus** [comment] 2023-03-09 10:45
@mifi 

Please check with weblate if you can lock a language for a specrifc users.
I'm agree that enable free edit of language could create problem (many of my tarnslationw as modified by people without a good knowledge of italian).

In the same time could be a problem for a translator like me.

But if you make a daily new build, iof course should cintain aletst language changes otherwise the translator that make some changes/update didn't see it,.

I made some changes on weblate but I cannot see it until you update github langauge file and create a new build.

A possible solution is quite simple.

**Enable in the application the loading of external language file.**

Then as translator I can load new language file and test it in the application.

Please remind that ther is my request to update your original strings

https://github.com/mifi/lossless-cut/issues/1498#issuecomment-1456104493

**Comment by mifi** [comment] 2023-03-10 05:30
good idea, i will add a command line to load external translation file.
