### ISSUE TITLE
360 vidéos

### ISSUE THREAD

**Issue by fifisave** [mifi/lossless-cut#294] opened 2020-04-07 07:47 UTC
hello,
may I suggest you to inject metadata to 360 vidéos when cut to stay VR compliant as is please?
LIke Spatial Media Metadata Injector does!
Regards

**Comment by mifi** [comment] 2020-04-07 14:07
I'm not sure if it's possible to do this with ffmpeg. I think this is a duplicate of #169 - please contribute there

**Closed by mifi** 2020-04-07 14:07 UTC
