### ISSUE TITLE
audio tracks manipulation

### ISSUE THREAD

**Issue by gruianovac** [mifi/lossless-cut#1463] opened 2023-02-06 18:23 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I want to be able to cut and move pieces of the audio track

**Comment by mifi** [comment] 2023-02-07 11:34
You can do this but it needs to be done in a separate step. (duplicate of #216 #976 )

**Closed by mifi** 2023-02-07 11:34 UTC
