### ISSUE TITLE
Ubiquitous mp4 video is not natively supported

### ISSUE THREAD

**Issue by kaihendry** [mifi/lossless-cut#263] opened 2020-02-28 06:49 UTC
Using 3.8.0-1 on Arch.
![image](https://user-images.githubusercontent.com/765871/75517349-71f8fc00-5a39-11ea-9f84-180fe43b7059.png)

It's unable to trim the file:
```

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'mike.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
  Duration: 00:03:36.67, start: 0.000000, bitrate: 513 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 160 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 345 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
```

How does that make sense?

**Comment by mifi** [comment] 2020-02-28 09:27
That doesn't make sense at all if there are only these 2 streams there. These are indeed supported codecs. Same problem with newest version? If you can share a file I can look into it. Or send me privately mikael@yankee.no

**Comment by kaihendry** [comment] 2020-02-28 14:27
https://s.natalian.org/2020-02-28/mike.mp4

**Comment by mifi** [comment] 2020-02-28 15:58
I am unable to reproduce this with your file. Did you by any chance accidentally convert to friendly format/codec from the menu? Could you provide log from the developer console as described in the new issue template?

**Comment by mifi** [comment] 2020-04-11 06:06
Since I tried your file and it works here, I'm going to close this. Please reopen if still an issue

**Closed by mifi** 2020-04-11 06:06 UTC
Labels: Cannot reproduce, bug
