### ISSUE TITLE
failed to trash source file

### ISSUE THREAD

**Issue by svefro** [mifi/lossless-cut#426] opened 2020-07-17 08:10 UTC
Deleting the source file seems to fail 50% off the time.
On windows you can not delete a file that is in use.
I know that is possible on linux and it might be on mac also.
Maybe there needs to be a delay before the actual file deletion after unloading the file from the player.

There should be a retry dialog if the file delete failed.

**Comment by happyfilmmaker** [comment] 2020-08-19 00:49
I've experience similar issues, usually with longer files. Trashing file usually fails, but even the permanent delete dialog errors with "Error: EBUSY: resource busy or locked, unlink (file)". 

Process explorer on windows shows that Lossless Cut is still holding onto the file even after it refreshes to a fresh screen, and so the app needs to be closed in order to even delete the file manually.

**Comment by nim56** [comment] 2020-09-02 16:39
I am having the same problem about 50% of the time, I have to close the app and manualy delete the file.

**Comment by mifi** [comment] 2020-10-29 13:16
I think this is related to #272

**Comment by nim56** [comment] 2020-11-02 07:35
Yes I am having the same problems as #272 on Windows 10

**Comment by mifi** [comment] 2021-08-24 16:50
closing due to duplicate of that issue

**Closed by mifi** 2021-08-24 16:50 UTC
