### ISSUE TITLE
When navigating using keyframes (Alt+->), the Cut End should be 1 frame prior to the end keyframe selected

### ISSUE THREAD

**Issue by infuse2001** [mifi/lossless-cut#887] opened 2021-10-10 12:47 UTC
**Describe the bug**
When navigating using keyframes (Alt+->), the Cut End should be 1 frame prior to the end keyframe selected

**To Reproduce**
1. Open any video file 
2. Click on Alt+-> and/or Alt+<- to navigate to Cut Start. 
3. Then Click on Alt+-> or Alt+<- to navigate to Cut End.
4. Then click on E and E again to export the section
3. View the exported video and See error as at least 1 extra frame after the desired Cut End. This extra frame is the Cut End keyframe which was not desired.

**Expected behavior**
While the Cursor for the Cut End is at the 1st Keyframe of the next segment, that frame should NOT be included in the exported video. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (x64) Version 1903 (build 18362.267)

**Additional context**
I currently have to navigate using Alt+-> to Cut Start, mark I, then navigate using Alt+-> to Cut End and finally, press the "," key to navigate to 1 frame prior. This gives a clean export but is a much slower process.

**Comment by mifi** [comment] 2022-02-13 15:49
I think what you're seeing is the same as this issue https://github.com/mifi/lossless-cut/issues/330#issuecomment-1009702161

The problem is that the behavior you're describing, where you need to go **1 frame back** to include the keyframe varies from file to file and cut mode. Is it correct that you were cutting using "Normal cut"? I believe if you change to "Keyframe cut" mode, it will be the opposite behavior (e.g. you need to move the cursor **one frame forward**) to include the keyframe. But again this also depends on the format/codec. For some files you don't need to do it at all. I'll close this issue and track this bug in the other issue, as it's something that affects many users.

**Closed by mifi** 2022-02-13 15:49 UTC
Labels: enhancement
