### ISSUE TITLE
[Linux 64 bit] v1.8.0 YARA Signature found

### ISSUE THREAD

**Issue by legendarynacar** [mifi/lossless-cut#49] opened 2017-11-08 09:37 UTC
# MAIN SOURCE : 
https://www.hybrid-analysis.com/sample/52037cc4c9248e8891b28ad98150b62b3286946b7e6d33440ef871209329ffd9?environmentId=300

## YARA signature match
details : 

> YARA signature "ldpreload" classified file "52037cc4c924elf.bin" as "backdoor" based on indicators: "dlopen,dlsym,fopen,FOPEN,fOpen,fopen64,__fxstat,__fxstat64,Accept,accept,610063006300650070007400,ACCEPT,__lxstat,__lxstat64,open,Open,oPen,OPEN,opEn,opeN,rmdir,__xstat,__xstat64,unlink,Unlink,fdopendir,opendir,OpenDir,openDir,readdir,Readdir,ReadDir,readdir64" (Reference: https://stuff.rop.io/, Author: xorseed)

source:

> YARA Signature

relevance:

> 10/10

research: `Show me all reports matching the same indicator` https://www.hybrid-analysis.com/search?query=indicatorid%3Ayara-0

**Comment by mifi** [comment] 2017-11-08 09:46
What does this mean and what's the problem?

**Comment by legendarynacar** [comment] 2017-11-08 11:05
Read this: http://securityintelligence.com/signature-based-detection-with-yara/

The reason you get this alter is  you have similar signatures with malwares in your linux64bit file. I did not check your 32 bit file.

**Comment by mifi** [comment] 2017-11-08 11:10
The executable is generated by electron-packager, so I don't have any control of this. I suspect this is caused by ffmpeg binary being bundled into the application. ffmpeg binaries for linux are fetched from the officially linked repo https://www.johnvansickle.com/ffmpeg/

**Comment by mifi** [comment] 2017-11-08 11:10
Is there any way we can remove this warning?

**Comment by legendarynacar** [comment] 2017-11-09 14:40
I might cant help you cuz I am not good at fixing rather then finding things.

I think you don't need to worry if you have no control of it since your codes are open. Tho at least check some generated softwares cuz they might be the reason.

**Comment by mifi** [comment] 2017-11-21 21:30
I will close this since I don't know how to fix it and it seems not such a big issue.

**Closed by mifi** 2017-11-21 21:30 UTC
