### ISSUE TITLE
Disabling overwrite still exports segments and does not save time on export

### ISSUE THREAD

**Issue by SignpostMarv** [mifi/lossless-cut#1691] opened 2023-08-25 16:42 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

1) Disable overwrite
2) Enable experimental cutting
3) Create many segments in a multi-hour video with at least one 2 hour segment
4) Export
5) Export again

### Expected behavior

LosslessCut should zip through all the exports and effectively do nothing.

### Actual behavior

LosslessCut exports the videos with filenames like `2023-08-22-smartcut-segment-copy-4.mp4` and promptly deletes them when done.

**Comment by mifi** [comment] 2023-08-27 18:43
this problem is only related to the experimental smart cut feature, right?

**Comment by SignpostMarv** [comment] 2023-08-27 18:44
> this problem is only related to the experimental smart cut feature, right?

will make a mental note to test without it, just felt it important to include that was part of the issue.

**Comment by snakecase** [comment] 2023-09-05 15:19
> this problem is only related to the experimental smart cut feature, right?

No, default export settings are enough to reproduce.
![LosslessCut_2023-09-05_20-18-19](https://github.com/mifi/lossless-cut/assets/4579891/a26bcb65-787a-4d45-b65b-e288e406bc39)

**Comment by mifi** [comment] 2023-09-05 20:24
@snakecase this is because you're using "merge" export mode. This will delete all segments after merge is complete, thus the files cannot be reused. Then it will create a new random suffixed file `xx-cut-merged-1693944979865.mp4`.
If you instead choose `Merge & separate` it should reuse all the exported segments next time (but the merge operation will still be re-done because it wouldn't result in overwriting output). Or wasn't that what you wanted?

**Comment by snakecase** [comment] 2023-09-06 09:17
Got it, thanks.

**Comment by mifi** [comment] 2024-08-07 14:35
closing for now, can reopen if still a problem

**Closed by mifi** 2024-08-07 14:35 UTC
