### ISSUE TITLE
ASF Files Not Cutting At Correct Time

### ISSUE THREAD

**Issue by Vguitarist** [mifi/lossless-cut#552] opened 2020-12-14 00:56 UTC
- [X ] I have tested the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- [X] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [X] I have searched for similar issues

Trying to cut a security ASF video using the latest LC portable release. I'm exporting it to ASF. No errors...but the file is cutting a 1-2 minutes earlier than the marker. I've tried compensating by marking the relative difference between marked time and cut time, but that doesn't work. I have no issues with other MPG file types...just ASF. Any advice?

**Comment by mifi** [comment] 2020-12-14 14:08
What is the distance between keyframes?

**Comment by Vguitarist** [comment] 2020-12-14 19:00
Hello Mikael,

 

Thank you for the quick reply. This video is a 30 minute extraction from my security DVR. There are no transitions or effects…just a sustained video stream. My OpenShot video editor doesn’t show any keyframes. Of course, I could use OpenShot to cut the video where I want, but I need the output to be lossless as it is dark outside and detail must be preserved. Thoughts?

 

Thanks

**Comment by mifi** [comment] 2020-12-14 21:21
If you turncon keyframes in losslesscut, do you see any keyframes? Maybe they are minutes apart? Or is it possible to share a clip that shows the problem. You could send to finstaden@gmail.com

**Comment by Vguitarist** [comment] 2020-12-14 22:41
There are no keyframes in the video, but keyframe cut was enabled in the settings. I switched it to normal and the output is now correct. Thanks for the help.

**Comment by mifi** [comment] 2020-12-14 23:09
Oh, that's great that it works with normal cut. Would be interesting to see such a file that has no keyframes.

**Comment by mattack1** [comment] 2020-12-14 23:15
Even though this is almost certainly a VERY VERY rare situation, I would expect an app to put up an error dialog in this case (and perhaps suggest turning off keyframe cut).

**Comment by mifi** [comment] 2020-12-15 10:10
Yea, the problem is I haven't seen any file that demonstrates this problem, so I cannot implement and test it

**Comment by mifi** [comment] 2021-08-24 16:29
closing as possible dup of #516

**Closed by mifi** 2021-08-24 16:29 UTC
