### ISSUE TITLE
Keyframe cut mode bug?

### ISSUE THREAD

**Issue by plztrial4me** [mifi/lossless-cut#1795] opened 2023-11-30 07:21 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

The input and output files I used for our tests are shared in the Google Drive link below.
https://drive.google.com/drive/folders/1cXTjbB4ooRaePtBhRgN9-nseS59oTibL?usp=sharing

The keyframes for the input file are shown below.

0.000000 (framnum=0)
3.000000 (framnum=90)
6.000000 (framnum=180)
9.000000 ...
12.000000
15.000000
18.000000
21.000000
24.000000
27.000000
30.000000

### Expected behavior

If you cut using the key frames 3.000000 (framnum=90) and 6.000000 (framnum=180) for both the start and end points, the result should be framed from 90 to 179.
(Note that FFMPEG does not include the last frame).

### Actual behavior

However, if you look at the output, it contains frames 90 to 179, as well as 180 (I frame) and 184 (P frame).
(Note that frames 181-183 are not included; they are all B frames).

I'm assuming this is an FFMPEG bug.

Singularity
1. When cutting with stream copy method for the same point in avidemux, the result is 90 to 179, the same as the expected behavior.
2. Even if the input file consists of only I frame and P frame, the result is changed from 90 to 179 when using ffmpeg.

### Share log

The ffmpeg command executed by losslesscut.

ffmpeg -hide_banner -ss '3.00000' -i 'D:\sample-framenum.mp4' -t '3.00000' -avoid_negative_ts make_zero -map '0:0' '-c:0' copy -map '0:1' '-c:1' copy -map_metadata 0 -movflags '+faststart' -default_mode infer_no_subs -ignore_unknown -f mp4 -y 'D:\sample-framenum-00.00.03.000-00.00.06.000.mp4'

**Comment by mifi** [comment] 2023-12-02 10:12
I can reproduce the problem.

- Only if I cut **to** 05.933 = **frame 178** (instead of 06.000 = frame 180), then the last frame visible in the output video is 179.
- If I cut to 05.900 (frame 177) then the last visible output frame is 178
- If I cut to 05.867 (frame 176) then the last visible output frame is still 178
- If I cut to 05.833 (frame 175) then the last visible output frame is still 178
- If I cut to 05.800 (frame 174) then the last visible output frame is still 178
- If I cut to 05.767 (frame 173) then the last visible output frame is still 178
- If I cut to 05.733 (frame 172) then the last visible *output frame is 174*

according to avidemux
- frame 184 in an P-frame
- frame 183 in an B-frame
- frame 182 in an B-frame
- frame 181 in an B-frame
- **frame 180** in an I-frame
- frame 179 in an P-frame
- **frame 178** in an P-frame
- frame 177 in an B-frame
- frame 176 in an B-frame
- frame 175 in an B-frame
- frame 174 in an P-frame
- frame 173 in an B-frame
- frame 172 in an B-frame

not sure what to make of this though. Unfortunately I will have to close this because there's nothing I can do about this problem, but I added a reference to this issue in #1216

If any more information comes up, we can re-open.

**Closed** 2023-12-02 10:13 UTC
