### ISSUE TITLE
Attempting to use an EDL from Channels DVR and getting `e.replace is not a function`

### ISSUE THREAD

**Issue by marknorgren** [mifi/lossless-cut#879] opened 2021-10-04 01:30 UTC
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
- If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.
- If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)
- Please provide the error report if you got one (Menu: Help -> Report an error)

**Describe the bug**
Loaded an mpg file and imported the EDL file Channels DVR created and I am getting  `e.replace is not a function` when attempting to run.

**To Reproduce**
1. Open mpg file
2. Click on Import -> Project -> EDL
3. Press `Export+Merge`
3. See error `e.replace is not a function`

**Expected behavior**
Export created with EDL cutlets.

**Screenshots**
<img width="358" alt="ScreenShot-2021-10-03-at-20 23 17@2x" src="https://user-images.githubusercontent.com/205066/135781234-d2976849-f2f0-45e8-bb0e-6779cab1e8a4.png">

**Desktop (please complete the following information):**
 - macOS 11.6 - MacBook Pro M1

**Additional context**

**Comment by micahed** [comment] 2021-12-21 13:22
Not the OP but this can reproduce this when importing comskip EDL files.
I've attached the comskip.edl file and the lossless-cut.llc file. 
Hovering over the Export+merge button shows it expects to export 5 segments, not 4


[lossless-cut.llc.txt](https://github.com/mifi/lossless-cut/files/7755575/lossless-cut.llc.txt)
[comskip.edl.txt](https://github.com/mifi/lossless-cut/files/7755576/comskip.edl.txt)
![lossless-cut-screenshot](https://user-images.githubusercontent.com/5658941/146936996-2753690b-0fa0-4498-98fe-c406b11179e0.png)

**Comment by mifi** [comment] 2021-12-22 07:18
Thanks! I've identified the bug. The problem was that mplayeEdlType was being created and it was not string. Have fixed it and fix will be included in the next version.

**Closed by mifi** 2021-12-22 07:18 UTC
Labels: enhancement
