### ISSUE TITLE
aivx on export

### ISSUE THREAD

**Issue by bevels** [mifi/lossless-cut#1110] opened 2022-04-11 01:44 UTC
Exported files from my Sony A7IV - Mov - Quicktime / MOV (Detected) - won't play in any media player. VLC error is...

_VLC could not decode the format "aivx" (No description for this codec)_

The files cannot be edited in Premiere Pro either, a similar "aivx" error occurs when trying to import the files.

Windows 10 X64

**Comment by mifi** [comment] 2022-04-11 04:56
if you could provide the requested info, or a sample file, then I can try to look into it

**Comment by mifi** [comment] 2022-04-15 04:52
possibly related #280

**Comment by mifi** [comment] 2022-07-25 10:00
closing as duplicate of #280 then

**Closed by mifi** 2022-07-25 10:00 UTC
