### ISSUE TITLE
Special characters in path like # break app

### ISSUE THREAD

**Issue by ndarville** [mifi/lossless-cut#40] opened 2017-08-15 10:22 UTC
> Not allowed to load local resource: `file:///C:/Users/ndarville/Downloads/#foo\nar\LosslessCut-win32-x64\resources\app.asar/index.html`

As you can see, the slashes are both forwards and backwards here; UNIX ones before the `#` and Windows ones after. Moving the folder to `Downloads/` resolves the problem.

I don’t know much about handling paths in JS, otherwise I’d just do a pull request.

This is on Windows 10.

**Comment by mifi** [comment] 2017-08-15 12:03
Hopefully fixed in 8fccd53a1854975569d9d3e0d1090b8a63ccdd24

**Comment by Shakil-Shahadat** [comment] 2020-12-12 02:58
I had the same issue with extracted `LosslessCut-win.zip`, in my case, the console said `Not allowed to load local resource: file:///G:/#Soft%20BackUp\Portable\LosslessCut\resources\app.asar\build\index.html`. But didn't have any issue with `D:\Download\Soft\LosslessCut-win`.

Also, `LosslessCut-win.exe` ran completely okay from `G:\#Soft BackUp\Portable`. Perhaps, the issue is solved for `LosslessCut-win.exe` but not for extracted 'LosslessCut-win.zip`.

**Comment by mifi** [comment] 2020-12-13 13:35
Thanks for pointing out. Seems this got broken again during a refactoring. I have now fixed it again

**Comment by Shakil-Shahadat** [comment] 2021-01-26 04:15
This issue can be closed now.

**Closed** 2021-01-26 11:16 UTC
