### ISSUE TITLE
it says unsupported file

### ISSUE THREAD

**Issue by skanull** [mifi/lossless-cut#776] opened 2021-07-04 08:57 UTC
I don't know what's wrong but it always display "unsupported file" whatever file I open. I tried mkv, mp4, and mov. I also tried "convert to supported format" but it shows up as failed to convert file.

Version: 3.36.0
OS: Windows 10

**Comment by SignpostMarv** [comment] 2021-07-20 17:27
This occasionally happens when:
* opening multiple lossless cut windows in quick succession followed by closing some of them before the rest have finished loading.
* the file is locked
* the file is corrupted

**Comment by mifi** [comment] 2021-08-24 15:27
Cannot look into this without more info. Closing for now

**Closed by mifi** 2021-08-24 15:27 UTC
Labels: need info

**Comment by SignpostMarv** [comment] 2021-10-17 22:53
Difficult to reproduce, but this can also happen if trying too rapidly to goggle playback with the spacebar after seeking with the mouse when the video file is loaded from a relatively slow hard disk.

**Comment by mifi** [comment] 2021-10-21 09:41
That's interesting. We are talking about this message, right?
<img width="366" alt="Screenshot 2021-10-21 at 16 38 39" src="https://user-images.githubusercontent.com/402547/138252203-7b374f57-32aa-49ca-8507-c6a011cda96c.png">

As far as I know, the video has not been loaded at all when this message shows

**Comment by SignpostMarv** [comment] 2021-10-21 10:01
I'll endeavour to pay more attention to the message next time it happens 👍

**Comment by ZzZombo** [comment] 2022-07-22 11:36
I'm not sure if this is the same problem as mine, but for me pretty much every other file in row is reported as unsupported. This can't be right, they all were recorded using NVIDIA ShadowPlay with the same settings. This is bizarre, but totally how it is for me. Every odd file is processed normally, but every even file is "unsupported". Twice I also encountered a problem where a file previously w/o this issue became suddenly "unsupported" after I marked the start of a segment.

**Comment by mifi** [comment] 2022-07-22 11:51
@ZzZombo  could  you check developer tools if there is any clues of an error there? (tools -> toggle developer tools)

**Comment by ZzZombo** [comment] 2022-07-22 13:20
```
userOpenFiles
main.3131d877.js:2 I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 17.29.22.21.DVR.mp4
I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4
main.3131d877.js:2 loadMedia I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 17.29.22.21.DVR.mp4 B:\edited-video undefined
main.3131d877.js:2 state reset
main.3131d877.js:2 ffprobe -of json -show_chapters -show_format -show_entries stream -i 'I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 17.29.22.21.DVR.mp4' -hide_banner
main.3131d877.js:2 formats mov,mp4,m4a,3gp,3g2,mj2
main.3131d877.js:2 fileType detected format {"ext":"mp4","mime":"video/mp4"}
main.3131d877.js:2 onDurationChange 299.836
main.3131d877.js:2 ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json 'I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 17.29.22.21.DVR.mp4'
main.3131d877.js:2 ffprobe -v error -read_intervals '0%33.716745' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json 'I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 17.29.22.21.DVR.mp4'
main.3131d877.js:2 loadMedia I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4 B:\edited-video undefined
main.3131d877.js:2 state reset
main.3131d877.js:2 ffprobe -of json -show_chapters -show_format -show_entries stream -i 'I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4' -hide_banner
main.3131d877.js:2 formats mov,mp4,m4a,3gp,3g2,mj2
main.3131d877.js:2 fileType detected format {"ext":"mp4","mime":"video/mp4"}
main.3131d877.js:2 onDurationChange 299.888333
main.3131d877.js:2 ffprobe -v error -read_intervals '0%30' -show_packets -select_streams 0 -show_entries 'packet=pts_time,flags' -of json 'I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4'
main.3131d877.js:2 onVideoError PIPELINE_ERROR_DECODE: VDA Error 4 3
(anonymous) @ main.3131d877.js:2
Ve @ main.3131d877.js:2
Ke @ main.3131d877.js:2
(anonymous) @ main.3131d877.js:2
Ar @ main.3131d877.js:2
Nr @ main.3131d877.js:2
(anonymous) @ main.3131d877.js:2
Le @ main.3131d877.js:2
(anonymous) @ main.3131d877.js:2
Mr @ main.3131d877.js:2
Jt @ main.3131d877.js:2
Zt @ main.3131d877.js:2
main.3131d877.js:2 Trying to create preview
main.3131d877.js:2 readFormatData I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4
main.3131d877.js:2 ffprobe -of json -show_format -i 'I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4' -hide_banner
main.3131d877.js:2 html5ifyAndLoad {speed: "fastest", hasVideo: true, hasAudio: true, usesDummyVideo: true}
main.3131d877.js:2 Making HTML5 friendly dummy {filePathArg: "I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4", outPath: "B:\edited-video\Path of Exile 2022.05.04 - 19.39.52.22.DVR-html5ified-dummy.mkv"}
main.3131d877.js:2 readFormatData I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4
main.3131d877.js:2 ffprobe -of json -show_format -i 'I:\home\documents\videos\Path of Exile\Path of Exile 2022.05.04 - 19.39.52.22.DVR.mp4' -hide_banner
main.3131d877.js:2 ffmpeg -hide_banner -f lavfi -i 'anullsrc=channel_layout=stereo:sample_rate=44100' -t '299.888' -acodec flac -y 'B:\edited-video\Path of Exile 2022.05.04 - 19.39.52.22.DVR-html5ified-dummy.mkv'
main.3131d877.js:2 
main.3131d877.js:2 onDurationChange 299.888
```

The first file opened normally, the second again had this problem. This is all console output since the moment I opened the 1st.

**Comment by mifi** [comment] 2022-07-24 01:51
@ZzZombo does the error popup just say "unsupported file", and nothing else? And what happens after that? if you press play, what happens?

**Comment by ZzZombo** [comment] 2022-07-24 03:59
No, it is says the file is unsupported natively and so the preview may be lacking, it then loads a very low quality video w/o audio. It plays as that.

**Comment by mifi** [comment] 2022-07-24 04:01
Oh, that's not an error. It's working as expected - it means that the player cannot play back the file and instead provides the low quality fallback.

**Comment by ZzZombo** [comment] 2022-07-24 05:25
Every second file? All recorded with the same settings by the same software? I seriously doubt it works as expected in this regard.

**Comment by mifi** [comment] 2022-07-24 05:38
PIPELINE_ERROR_DECODE indicates that the html5 video player has trouble playing back the file for some reason. This might get fixed once we upgrade to a newer Electron version. For now, lossslesscut will try to do the next best thing and use the fallback preview.

You can try:
- Disable "Auto convert to supported format" in settings
- Disabling or enable hardware acceleration of h264 decoding if possible in your operating system
