### ISSUE TITLE
Incorrect time display and the output tag don't support  language not english.

### ISSUE THREAD

**Issue by kebinzhi** [mifi/lossless-cut#449] opened 2020-08-31 10:41 UTC
1、Incorrect video duration —— When playing the output video, sometimes the duration of video is longer and the longer part cannot be played.
2、I enter some tags in Chinese, the tag text in output video name is replace with  ‘____’.

Can you fix this?

**Comment by mifi** [comment] 2020-11-15 20:52
1. try to disable all tracks except video and see if it helps
2. the problem is that not all file systems may support all these kinds of special characters, so losslesscut would need to know which file system the user is trying to save to

**Comment by mifi** [comment] 2020-12-11 12:43
closing in favor of #427

**Closed by mifi** 2020-12-11 12:43 UTC
