### ISSUE TITLE
Remember (initial) window size and position on desktop?

### ISSUE THREAD

**Issue by bsto** [mifi/lossless-cut#116] opened 2019-01-31 09:39 UTC
Whenever I start LC it is placed/opened initially in the center of the screen.
I always have to resize and move it manually. This is unnecessary.

Is there a way to let LC automatically remember last size and position on desktop (...and re-use it at next startup)

Or can this feature be added in the next release?

Thank you
Ben

**Comment by mifi** [comment] 2019-01-31 19:01
duplicate of #44
will implement when i have time

**Closed by mifi** 2019-01-31 19:01 UTC
