### ISSUE TITLE
Configuration loss since 3.24

### ISSUE THREAD

**Issue by shinnlu** [mifi/lossless-cut#510] opened 2020-11-24 06:34 UTC
- [ Y ] I have tested the newest version
problem occur with 3.24, 3.25
- [ Y ] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [ Y ] I have searched for similar issues

i have many files cut with 3.23.7, after upgrade to 3.24 and 3.25, configuration loss randomly after video loaded.

![image](https://user-images.githubusercontent.com/570246/100057063-b4812500-2e61-11eb-94d3-5bc9096fcae5.png)

left: 3.23.7, right:3.24
![image](https://user-images.githubusercontent.com/570246/100057247-0b86fa00-2e62-11eb-957f-3e65bce20f29.png)

**Comment by mifi** [comment] 2020-11-24 11:01
Thanks for reporting. will look into it. have now demoted these versions to pre-release

**Comment by mifi** [comment] 2020-11-24 11:39
So the problem is that some of the segments disappear randomly? Or what do you do to make them disappear?

**Comment by shinnlu** [comment] 2020-11-24 11:46
i didn't do anything, just upgrade to new version and load previous video then found the segment missing.
if you need my video, i can upload to some web space.

**Comment by mifi** [comment] 2020-11-24 11:56
Ok if you can share your CSV that would be nice

**Comment by shinnlu** [comment] 2020-11-24 13:02
here is my video and csv file.
[link](http://twycf.com/tmp/)

**Comment by mifi** [comment] 2020-11-24 15:25
Thanks. For me it loads all 24 segments. Are you running many LosslessCut instances at the same time, or just one?

**Comment by mifi** [comment] 2020-11-24 15:45
Also, did you load your video twice? I can see from your log that it opened the file twice

**Comment by shinnlu** [comment] 2020-11-25 01:29
i think i found the problem.
i have upload a new video to the web space, please download it.
1. drag '20 Minute HIIT Workout at Home.mp4', 24 segment loaded
2. drag '2.4 minutes workout.mp4', still 24 segment, but the video has only 11 segment

**Comment by mifi** [comment] 2020-11-25 21:47
Thanks! I can reproduce it now. Will look into it

**Comment by mifi** [comment] 2020-11-25 22:54
Ok I have now fixed the issue. Will be out in the next version! thanks for you help

**Closed by mifi** 2020-11-25 22:54 UTC

**Comment by shinnlu** [comment] 2020-11-26 02:28
thank you, it's fixed in 3.26.
