### ISSUE TITLE
Merge bug

### ISSUE THREAD

**Issue by toshi-AG** [mifi/lossless-cut#684] opened 2021-02-25 02:47 UTC
please help me. After cutting the unnecessary part of one video with "Keyframe cut", it was combined with "Merge cut". However, when I try to play it, the video stops for a moment (0.5 seconds) at each joint.
When I zoomed in on the problem area, I found that there were more than 10 identical frames attached to the last part of the previous scene. Why do these problems occur?
The specified version is "Ver 3.33.1", but it was the same in the previous version.
Please tell me the solution.

**Comment by markusd1984** [comment] 2021-02-25 13:02
Did you use the default keyframe cut or perhaps may have switched the **cut mode** to "normal cut"? Try it out...

@mifi we may need to have some better/more explanation in the export view/tool tip?

**Comment by toshi-AG** [comment] 2021-02-25 13:21
![WS07](https://user-images.githubusercontent.com/79617260/109159217-b7b8e380-77b7-11eb-9859-cab1cccace33.JPG)
![WS08](https://user-images.githubusercontent.com/79617260/109159225-bb4c6a80-77b7-11eb-9362-1331af26db23.JPG)

**Comment by toshi-AG** [comment] 2021-02-25 13:23
Thank you for your response.
Keyframe is cut with the default "Keyframe cut".
"Seek Keyframe" is cut to fit the keyframe.

**Comment by markusd1984** [comment] 2021-02-25 17:15
But have you tried normal cut instead?? To see if the issue is not there? ;)

**Comment by toshi-AG** [comment] 2021-02-25 22:10
Thank you for your reply.
I also tried "Mormal cut" but it didn't work.
Please check the attached video of the problem.

**Comment by toshi-AG** [comment] 2021-02-25 22:10
Uploading 初飛行01b-cut-merged-1614290969785.MP4…

**Comment by toshi-AG** [comment] 2021-02-25 23:08
The cause of the problem has been determined.
It seems that problems occur when the resolution of the image is large.
The video resolution I used was 2.7k (2720x1530 pixel) and I had a problem.
I tried it experimentally at a lower resolution and it didn't cause any problems.
There seems to be no problem up to Fuu HD (1920x1080 pixcel).
I don't know the design specifications, but I definitely want you to improve it so that it can be used in high resolution.
Because LossLess works only at high resolutions.
Please let me know if my judgment is wrong.

**Comment by mifi** [comment] 2021-03-02 04:54
Your upload did not work so i cannot look into this unfortunately.

**Comment by toshi-AG** [comment] 2021-03-02 14:34
https://user-images.githubusercontent.com/79617260/109663775-cfc1a600-7baf-11eb-8e00-71bc66fe79f4.MP4

**Comment by toshi-AG** [comment] 2021-03-02 14:55
Thank you for your response, mifi.
I wrote in the previous comment that it "affects video size", but that seems to be wrong.
I didn't understand the reason anymore and gave up.
One thing I found out is that the frame rate of files edited with "Loss Less Cut" is low.
Why does the frame rate change even though it is lossless?
Attach the properties of the edited video file. 29.97FPS → 17.29FPS. Why?

**Comment by mifi** [comment] 2021-03-03 06:09
I need two source files that can be merged to reproduce the problem

**Closed** 2021-03-03 11:44 UTC

**Comment by toshi-AG** [comment] 2021-03-03 12:04
Even if the video is shortened, it will exceed 10MByte and cannot be sent.
Isn't this problem the fate of "Loss Less"?
Are other users working well?
I gave up sticking to "Loss Less".
Thank you for your support so far.
