### ISSUE TITLE
Preview has a Green cast

### ISSUE THREAD

**Issue by DasFragezeichen** [mifi/lossless-cut#1007] opened 2022-01-30 13:21 UTC
If I open a MP4 file, recorded with AnyMP4 Screen Recorder, the video screen has a green cast. Export is OK. With VLC the same file is good.
Other MP4 files, for example recorded with GoPro sceems to be OK. Any Idea?
![looslesscut_green](https://user-images.githubusercontent.com/75027968/151701339-afc2e61b-b531-4bc7-a601-820802894d10.png)

**Comment by mifi** [comment] 2022-02-12 09:15
that's odd. does the file have transparency by any chance? does it show up as "Not natively supported" when you open it? any possibility to share a short file with this issue?

**Comment by DasFragezeichen** [comment] 2022-02-12 19:33
Here is a file. Hope this helps. Thanks for your work.

https://user-images.githubusercontent.com/75027968/153725627-7f8f57c9-d561-4446-afb9-f8fa76f6fbbd.mp4

**Comment by mifi** [comment] 2022-02-13 11:31
Thanks. I tested your file and for me there is no green hue 🤔
Could you try on a different computer?

**Comment by mifi** [comment] 2022-02-24 09:01
closing as cannot reproduce

**Closed by mifi** 2022-02-24 09:01 UTC
Labels: bug, Cannot reproduce
