### ISSUE TITLE
Help/About LossLessCut is not working...

### ISSUE THREAD

**Issue by stoxopeus** [mifi/lossless-cut#239] opened 2020-01-04 14:06 UTC
Not very important, but the menu option Help/About LossLessCut is doing nothing in version 2.6.2 (on Windows 10)

**Comment by PartyLich** [comment] 2020-01-06 17:19
Glancing at [the commit that added the About menu on Windows and Linux](https://github.com/mifi/lossless-cut/commit/ce3a6d48b8b8b3c58e284d49551ca834ff5ceff1), it seems the author added an empty menu with a default role. That default role exists and has a defined action on Mac. Evidently there's no default behavior on other platforms. Electron docs reference: [here](https://github.com/electron/electron/blob/master/docs/api/menu.md#standard-menu-item-actions)

If anyone can try it on Mac and let me know what the intended behavior is, I'd be happy to implement it for the other platforms and open a PR. I obviously can't promise it will ever get merged though.

**Comment by mifi** [comment] 2020-02-11 15:06
There is just a single menu entry under help: "Learn more" that links to this repo

**Comment by PartyLich** [comment] 2020-02-12 12:02
It shows on windows (don't have time to check linux this morning) - it simply doesnt do anything. You can mouseover or click, but it doesn't display anything or otherwise respond to any action.
![image](https://user-images.githubusercontent.com/2792750/74333249-8ebce080-4d65-11ea-8717-4a3bff2bfc97.png)
So one expects a response from interacting with a UI element, but they get nothing

**Comment by mifi** [comment] 2020-02-12 12:14
Ok I see. Seems only supported on windows: https://github.com/electron/electron/issues/10153

**Comment by mifi** [comment] 2020-03-26 13:21
Now fixed

**Closed by mifi** 2020-03-26 13:21 UTC
Labels: enhancement

**Comment by abhimatta** [comment] 2020-09-03 16:49
@mifi were you able to solve this issue?

**Comment by mifi** [comment] 2020-11-26 19:46
have u tried newest version?
