### ISSUE TITLE
Excessive flickering when cutting

### ISSUE THREAD

**Issue by Tomahawk27x** [mifi/lossless-cut#2083] opened 2024-07-22 09:49 UTC
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 10

### Steps to reproduce

Open file, then just seek around.

### Expected behavior

Smooth seeking without any blank screens, flickering and stutters

### Actual behavior

https://github.com/user-attachments/assets/5367a535-0b4e-4d7d-ba67-6b5b314cc641

This has happened everytime I tried to use the app.

**Comment by mifi** [comment] 2024-07-22 10:19
does it happen when you playback also? or just when you seek? does it happen with all files? do you have any other computer to try on?

**Comment by Tomahawk27x** [comment] 2024-07-23 15:31
Okay so I actually had some old videos recorded on a craptop with OBS, some flickered some didn't. Different resolutions too, had some clips recorded with Shadowplay on a 4:3 monitor and no signs of flickering, very strange.

**Comment by mifi** [comment] 2024-07-23 19:45
some people had trouble with nvidia and losslesscut they changed some settings in the nvidia control panel (for losslesscut), see https://github.com/search?q=repo%3Amifi%2Flossless-cut+nvidia&type=issues

**Comment by mattack1** [comment] 2024-07-24 00:52
I noticed a similar thing, on MacOS.. But I'm usually editing MPEG2 files (SD files downloaded from my Tivo), which LLC doesn't support natively (so I can't actually just play with audio).. but a recent change seems to make it get video frames more quickly (GOOD), but IIRC it always flashes black then shows the video frame.

But it's still faster at showing the frame than it used to be.

**Comment by Tomahawk27x** [comment] 2024-07-25 15:36
> some people had trouble with nvidia and losslesscut they changed some settings in the nvidia control panel (for losslesscut), see https://github.com/search?q=repo%3Amifi%2Flossless-cut+nvidia&type=issues

I've already tried that and it doesn't make any difference, the only fix I know is turning on compatibility mode for LLC which was mentioned in a previous issue, but seeking isn't as smooth. No flickering, just lower framerates, so I was wondering if there was a nother fix without changing the compatibility.

**Comment by Tomahawk27x** [comment] 2024-07-25 15:36
Note that playback isn't an issue at all it goes perfectly normal it's just the seeking.

**Comment by mifi** [comment] 2024-07-28 20:53
@Tomahawk27x out of curiosity if you load the same if in google chrome and scrub through, does the same happen?

**Comment by mifi** [comment] 2024-08-01 13:55
it could be a problem with the current version of electron and might get solved when we upgrade

**Comment by mifi** [comment] 2024-08-07 15:38
electron has now been upgraded so you could try again with the latest version.

**Comment by Tomahawk27x** [comment] 2024-08-09 19:34
Unfortunately, no luck.

**Comment by Frizzle99** [comment] 2024-08-13 10:01
Hello. Not sure what github etiquette is, but I just made an account to say I have this problem as well. It started happening in version 3.61 for me. and is also present in 3.62

**Comment by mifi** [comment] 2024-08-13 15:26
@Frizzle99 which OS?

**Comment by Frizzle99** [comment] 2024-08-14 11:18
Windows 11 Pro 23H2. AMD 3700X CPU and 4070 Super graphics card.

**Comment by mifi** [comment] 2024-08-15 13:38
does it happen with all kinds of files? what if you try a simple mp4 h264 file like https://github.com/mifi/lossless-cut-fixtures/blob/master/hardangerbrua-dji-phantom.mp4

**Comment by Frizzle99** [comment] 2024-08-18 13:51
Sorry for the late reply. I went back to 3.59.1, Just reinstalled 3.62 and with your file it works fine. Then I tried other files and now they all seem fine too. Not sure what happened there but it seems the problem just solved itself. For me at least, not sure about OP obviously. I'm sorry for wasting your time, Mikael.

**Comment by Frizzle99** [comment] 2024-08-20 05:42
Back again. I failed to see the pattern before but now I noticed the problem is still there. It just -only- happens when the program converts to a supported format. So mostly WMV files and the like, not MKV/MP4

**Comment by mifi** [comment] 2024-08-27 20:23
@Frizzle99 I think your problem is different from OP. Maybe you can record a screencast

**Comment by Frizzle99** [comment] 2024-09-01 11:28
Sure. First file is an MP4 source file, working as intended. Second is a wmv file that the app had to convert, showing the black flickering on seeking.

https://github.com/user-attachments/assets/b8b8e24b-85f7-4c9f-85fd-f41327f14577


https://github.com/user-attachments/assets/affd2963-922e-4bfa-b4af-229f9aff1895

**Comment by Tomahawk27x** [comment] 2024-09-02 16:01
my files are mp4 yet they still flicker in the cutter

**Comment by mifi** [comment] 2024-09-02 20:51
@Frizzle99 

> WMV.problem.mp4

This is because of ffmpeg assisted playback (see upper left corner): wmv is actually not supported but with the ffmpeg assisted playback it is supported. unfortunately the ffmpeg assisted playback has always been a bit crude and it's not super trivial to make it smoother but I will see if i can get it improved some day.

@Tomahawk27x your issue is a different problem (not ffmpeg-assisted playback) and unfortunately I have no idea what's causing it.

**Comment by Frizzle99** [comment] 2024-09-03 10:47
> @Frizzle99
> 
> > WMV.problem.mp4
> 
> This is because of ffmpeg assisted playback (see upper left corner): wmv is actually not supported but with the ffmpeg assisted playback it is supported. unfortunately the ffmpeg assisted playback has always been a bit crude and it's not super trivial to make it smoother but I will see if i can get it improved some day.


I know. It's always been like this with the app but it just started doing the black flicker in the latest version, which is why I added to the conversation here. As it does seem to be a different problem than OP is having I'll say sorry for trying to hijack his thread. ;)

**Comment by mifi** [comment] 2024-09-03 21:02
> I know. It's always been like this with the app but it just started doing the black flicker in the latest version, which is why I added to the conversation here. As it does seem to be a different problem than OP is having I'll say sorry for trying to hijack his thread. ;)

i did now manage to find a way to reduce this flickering (note again for new readers, it's not the same as OP's flicker)

**Comment by Kaggypants** [comment] 2024-09-10 02:49
Having the same issue when trying to cut mp4 and mkv files. Using Windows 11. Most of Lossless' menus look terribly distorted too, as if it's incorrectly trying to scale to a particular resolution.

https://www.youtube.com/watch?v=BJdn-uixKLg

**Comment by whoiskevinrich** [comment] 2024-09-17 22:52
[Possible Fix]
I have been able to control the flickering behavior by setting the "Multi-Frame Sampled AA (MFAA)" Setting to "Off" for the LosslessCut Application in the NVIDIA Control Panel as shown below.

I'd been having the issue for about a year and figured it was some Nvidia Setting.

![image](https://github.com/user-attachments/assets/7b38f50c-f64d-4d90-a24a-d82bf0891772)

**Comment by Tomahawk27x** [comment] 2024-09-21 09:02
thx it fixed it

**Comment by mifi** [comment] 2024-09-22 03:26
Ok closing this as it seems to be an nvidia bug

**Closed by mifi** 2024-09-22 03:26 UTC

**Comment by Kaggypants** [comment] 2024-09-22 03:50
Just FYI this did not fix it on my end as that setting is globally off in my control panel.

**Comment by mifi** [comment] 2024-09-22 03:55
Are you having the problem that [Frizzle99 is having](https://github.com/mifi/lossless-cut/issues/2083#issuecomment-2298011718) or OP’s problem?

**Comment by Kaggypants** [comment] 2024-09-22 04:19
> Are you having the problem that [Frizzle99 is having](https://github.com/mifi/lossless-cut/issues/2083#issuecomment-2298011718) or OP’s problem?

I'm having the issue mentioned by the OP. You can see it in the video I posted [here](https://www.youtube.com/watch?v=BJdn-uixKLg). I'd like to reemphasize that Lossless' menus look extremely distorted, as if they are displaying at the incorrect resolution. When I click on Lossless after having alt tabbed, the program 'refocuses' and gets rid of the distortion. I believe this is probably causing the flickering issues. As you can see in the attached image, both the menus in the upper left and the buttons in the lower right look distorted/blurry.

![blurry](https://github.com/user-attachments/assets/89452a23-773e-41e2-ad62-18fcbd22b762)

**Comment by mifi** [comment] 2024-09-22 04:42
Do you also have an nvidia gfx card? If so did you try all the nvidia specific workarounds like fps setting etc, from here https://github.com/mifi/lossless-cut/issues/2083#issuecomment-2246150616 ?
Also does it happen on other computers or just one one specific computer?

If not nvidia, what kind of graphics card do you have?

this is definitely a bug in the graphics driver, windows, or electron (or a combination of these). Unfortunately there’s no way for me to fix this, and we can only hope it gets fixed in the future by one of these parties, or some people find a workaround.

**Comment by Kaggypants** [comment] 2024-09-22 05:14
I've attached my hardware/software specs. Additionally, I am using a GSYNC monitor @ 120FPS.

[DxDiag.txt](https://github.com/user-attachments/files/17088381/DxDiag.txt)

Here is another video demonstrating the issue:

[](https://www.youtube.com/watch?v=NcvtmNCzpwM)

As you can see, when I try to use seeking it will only play for a short amount of time before returning to the beginning of the video and pausing. In the second half of the video, you can see when I try to maximize Lossless and then play the video, the flickering issue is introduced.

I have tried both .mkv and old .mp4 videos that I had no problem cutting in the past using Lossless.

This is really unfortunate since I love your program.

**Comment by Frizzle99** [comment] 2024-09-23 10:28
Okay this is getting out of control a little bit now :D 
I don't have the same problem as OP, nor Kaggypants from the looks of it. I do also have an nvidia card and a gsync monitor. Turning off gsync or MFAA doesn't help. My issue is just a bit annoying, but it isn't a big deal really. As I said it only happens on videos where the program has to convert the file in order to view or edit it, so it seems to be a problem with the latest version of ffmpeg. Hopefully it will go away with future versions. Thanks for your program Mikael.

**Comment by Kaggypants** [comment] 2024-10-08 06:43
I still have playback flickering in 3.63.0.0. When I try to maximize Lossless, the screen goes black. The UI text is also still distorted.

However, the videos are no longer resetting after 5 seconds when I hit play. Not ideal but serviceable at least.

**Comment by AwesomeAxolotl** [comment] 2024-10-26 09:37
The fixes don't work for me (nvidia settings I found suggested). Is there a good way to disable the html5fied playback? (the preview works without it)... not only the video flickers but the whole application. I encounter it when I try to switch from one video to the other because that's not possible to do with invoking the playback. Just opening one video and cutting it works without issues because I just have to avoid pressing play.

**Comment by HitoSarg** [comment] 2024-11-21 10:52
I found the solution for anyone still having this issue. It is in fact an Nvidia problem. You must disable Antialiasing - FXAA in Nvidia control panel to prevent applications in Windows 11 from having blurry text. In Lossless' case, this also caused the in-app media player to distort/flicker.
