### ISSUE TITLE
Timecode issue.

### ISSUE THREAD

**Issue by Doug183** [mifi/lossless-cut#1990] opened 2024-05-09 19:37 UTC
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

MacOS 12

### Steps to reproduce

I posted once before, but here are pictures to illustrate the issue.

0) I am using the latest download from GitHub - Lossless Cut 3.59.  However this problem can be recreated with older versions.
1) Main problem.  Lossless cut/FFMPEG use timing calculation in that thousands of second format.
2) Videos use frame rates.
3) There is a Time Code drift in Lossless Cut that is not accounted for.  This problem can be seen in other simpler video viewers as well (Quicktime X, VLC, FFMPEG, LossLess Cut.). 
3a) Adobe Premiere, AVID, and FCP do not have this issue.

Here is 49+ minute video compressed in  both H264 and ProResLT with a counter burned in.  
[H264 version](https://www.dropbox.com/s/xkbiu94drksg0ak/XD38924%20The%20Natural%20History%20Of%20Man%20The%20Time%20of%20Man_vwr_H264.mov?dl=0)
[ProResLT](https://www.dropbox.com/s/w5qwjq26g7gvd6w/XD38924%20The%20Natural%20History%20Of%20Man%20The%20Time%20of%20Man_vwr_ProResLT.mov?dl=0)

I created comparative screen shots using Lossless Cut and Adobe Premiere at the following time intervals:
6 seconds, 10 Minutes, and then in 5 minute increments and then two different endings.

<img width="806" alt="0006_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/c4d24a4c-83ed-4bbb-bbe0-8e7646c99b0c">
<img width="664" alt="0006_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/23ffc667-f45d-47e7-8dd1-1b51b8ba55ff">
<img width="812" alt="1000_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/da3124bb-72c4-406f-936f-17de28bcb9b0">
<img width="664" alt="1000_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/c6d612e3-495a-414e-b516-fb3c98ea2f16">
<img width="808" alt="1500_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/89f7d067-9870-4799-91aa-3b0d328c4dcd">
<img width="666" alt="1500_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/db495c19-641e-47b5-9520-e27d485673cd">
<img width="806" alt="2000_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/d4fa4f65-62a0-4266-a795-bbd5902422ca">
<img width="663" alt="2000_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/4cdfb16a-b5ee-42b9-a822-a0b0d9f974bc">
<img width="811" alt="2500_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/7b674c9c-ccdb-4053-90ca-d3aca1957e60">
<img width="666" alt="2500_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/b0ecce48-4ffc-4fce-8ebf-247f479bb9e1">
<img width="807" alt="3000_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/b89f28aa-132d-49a3-b59a-d1058fc8f535">
<img width="664" alt="3000_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/1a90cbfe-ec13-464e-a05c-9b7d9f790777">
<img width="806" alt="3500_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/7e699bed-137c-4ae0-9d8a-a555977b1fc5">
<img width="665" alt="3500_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/17c58b9e-3cae-4704-a44d-8052fd3d73cb">
<img width="809" alt="4000_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/c81d8c33-cf66-4a70-9d04-9ada1cdaf0ba">
<img width="664" alt="4000_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/7f1ab322-12da-4755-b55c-c283bdc0ff0b">
<img width="811" alt="4500_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/80459b3e-06c1-47f4-9215-757d1c5ffc6f">
<img width="666" alt="4500_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/9ce5630b-e443-4d8c-bfb9-8b53fe5641d8">
<img width="808" alt="490621_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/f73504b7-19ca-4801-aa26-963f9466bcc3">
<img width="665" alt="490621_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/3e669817-dd7e-41b0-9756-aa15321aea15">
<img width="807" alt="490921_LosslessCut_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/02fead1c-ab03-436b-aa4a-bf50c0e5fd12">
<img width="665" alt="490921_Premiere_v1" src="https://github.com/mifi/lossless-cut/assets/14873546/01762128-999d-4ea4-893e-77379323fb1f">

### Expected behavior

Time code should be spot on.

### Actual behavior

Time Code drifts.

**Comment by Doug183** [comment] 2024-05-09 19:42
Solution.
I have had code written for a custom Python script that uses FFMPEG to replace footage which handles the thousand timing issue to frames accurately.  I am happy to donate it to the project if someone tells me how.  Lossless cut is great app and I think is super valuable to the community.

**Comment by mifi** [comment] 2024-10-07 07:40
i will close this as a duplicate of #1470

**Closed by mifi** 2024-10-07 07:40 UTC
