### ISSUE TITLE
Make texts copyable

### ISSUE THREAD

**Issue by cyzs233** [mifi/lossless-cut#1088] opened 2022-03-22 07:05 UTC
It would be nice to be able to copy data from the current interface.
![Untitled](https://user-images.githubusercontent.com/25927091/159426163-2b10e713-258a-4391-8135-5a39d9c20a3c.png)

**Comment by mifi** [comment] 2022-05-09 19:40
closing as duplicate of #719

**Closed by mifi** 2022-05-09 19:40 UTC
