### ISSUE TITLE
[Feature Request] Allow cutting also externally added tracks (subtitle/audio/video)

### ISSUE THREAD

**Issue by Droyk** [mifi/lossless-cut#955] opened 2021-12-16 06:52 UTC
If the user adds subtitle as an additional track and then cut the part of the video the exported video doesn't come with the correct subtitle part 
![image](https://user-images.githubusercontent.com/15848350/146307247-4480c4c5-c0f3-42a5-bc30-f33e9f0ced16.png)
![image](https://user-images.githubusercontent.com/15848350/146308685-331a440a-0a37-449e-968a-a6e0c810a3aa.png)
![image](https://user-images.githubusercontent.com/15848350/146307279-d46f32b5-1a5a-4a84-bdb9-9a76231e5d31.png)

the exported video has the subtitle
![image](https://user-images.githubusercontent.com/15848350/146307478-576f2cce-f06f-49fb-a094-d8083e2f2462.png)
but it incorrectly cut the very first part of it 

```
1
00:00:57,408 --> 00:01:00,607
[POLICE SIREN WAILS]

2
00:01:37,608 --> 00:01:38,641
[HORN HONKS]

3
00:01:43,206 --> 00:01:45,542
- [ENGINE REVS]
- [HORN HONKS]

4
00:02:06,274 --> 00:02:08,271
[POLICE SIREN WAILING]

5
00:02:08,274 --> 00:02:09,873
DRIVER: Oh, shit.

6
00:02:12,274 --> 00:02:13,740
I bet you 100 I lose 'em.

7
00:02:15,974 --> 00:02:17,108
[ENGINE REVS]

8
00:02:19,542 --> 00:02:21,275
[TIRES SQUEAL]

9
00:02:23,706 --> 00:02:24,706
[GRUNTS]

10
00:02:28,074 --> 00:02:30,740
[SIREN CONTINUES]

11
00:02:43,139 --> 00:02:45,937
- DRIVER: That's 100 bucks you owe me.
- What?

12
00:02:45,939 --> 00:02:47,873
Your silence was your bet.
You know that, right?

13
00:02:50,774 --> 00:02:53,108
- [SIREN WAILS]
- Shit.

14
00:03:00,106 --> 00:03:01,140
Step out of the car.

15
00:03:01,639 --> 00:03:02,741
Step out of the car!

16
00:03:03,907 --> 00:03:05,972
- Show me your hands. Hands!
- My hands are right here.

17
00:03:05,973 --> 00:03:08,038
- COP 1: Step away!
- We on our way to the hosp...

18
00:03:08,040 --> 00:03:09,771
Listen to... Listen to me.

19
00:03:09,772 --> 00:03:11,605
- Stop resisting.
- Nobody's resisting you.
```
Wanted this part of it!
```
1
00:00:05,691 --> 00:00:08,321
- YVONNE: We should probably go out back.
- I specifically said,

2
00:00:08,324 --> 00:00:10,388
"Nothing for my birthday."

3
00:00:10,391 --> 00:00:11,691
I didn't... I...

4
00:00:13,757 --> 00:00:16,390
Everybody wanted to do something
and I just thought that...

5
00:00:16,391 --> 00:00:18,756
Yvonne, there are
very few things in my life

6
00:00:18,757 --> 00:00:19,926
I can control.

7
00:00:20,224 --> 00:00:21,823
And you know that.

8
00:00:21,824 --> 00:00:24,422
My time and the people
I choose to share it with

9
00:00:24,425 --> 00:00:25,689
are at the top of my list.

10
00:00:25,690 --> 00:00:26,756
I know.

11
00:00:26,757 --> 00:00:28,026
I'm sorry. I...

12
00:00:29,391 --> 00:00:33,193
[SIGHS] I'm gonna tell them
that they all should leave.

13
00:00:37,191 --> 00:00:38,325
Did you know about this?

14
00:00:39,324 --> 00:00:40,324
Huh?

15
00:00:41,992 --> 00:00:43,025
I'm sorry, P.

16
00:00:44,324 --> 00:00:46,859
I'm sorry you gotta have a surprise
party in your huge mansion.

17
00:00:47,592 --> 00:00:50,392
You gotta get a bunch of expensive
gifts from your rich friends.

18
00:00:50,725 --> 00:00:52,726
I'm sorry that you got
a thoughtful executive.

19
00:00:54,092 --> 00:00:55,659
Some of us got real problems.

20
00:00:56,224 --> 00:00:57,758
I'm fighting to see my son.

21
00:00:59,025 --> 00:01:00,056
Oh.

22
00:01:00,059 --> 00:01:01,391
I'm sorry, D.

23
00:01:02,257 --> 00:01:04,190
Is a single afternoon
with your son

24
00:01:04,191 --> 00:01:06,856
not enough to repair
the years of neglect?

25
00:01:06,859 --> 00:01:08,891
- Watch your mouth, man.
- And whose fault is it

26
00:01:08,892 --> 00:01:10,325
that you can't see him?

27
00:01:11,092 --> 00:01:12,159
Screw you.

28
00:01:12,758 --> 00:01:14,659
And screw
your damn privilege, man.

29
00:01:15,993 --> 00:01:17,493
And your attitude, man.

30
00:01:19,926 --> 00:01:21,560
[PANTING]

31
00:01:23,557 --> 00:01:24,592
Are you mad?

32
00:01:25,993 --> 00:01:27,026
You mad, P?

33
00:01:32,159 --> 00:01:33,391
[PANTING]

34
00:01:38,190 --> 00:01:39,425
What? You wanna break this?

35
00:01:40,525 --> 00:01:42,324
You wanna break
Carter's bottle of wine?

36
00:01:43,158 --> 00:01:45,590
Huh? You wanna break
this big-ass bottle of wine?

37
00:01:45,592 --> 00:01:46,825
Yes!

38
00:01:47,891 --> 00:01:50,191
- [SCREAMS]
- What else you wanna do, P?

39
00:01:53,324 --> 00:01:54,860
Hmm? You want this, right here?

40
00:01:58,224 --> 00:01:59,224
[GRUNTS]

41
00:02:01,926 --> 00:02:03,989
Th... The bull.

42
00:02:03,992 --> 00:02:05,359
I've always hated that.

43
00:02:07,892 --> 00:02:09,325
[GRUNTS]

44
00:02:09,926 --> 00:02:11,690
[SCREAMS]

45
00:02:11,691 --> 00:02:13,525
[PANTS]

46
00:02:14,225 --> 00:02:15,325
The portrait.

47
00:02:16,557 --> 00:02:17,926
No, no! Not that one.

48
00:02:18,190 --> 00:02:19,225
- This one?
- No.

49
00:02:19,926 --> 00:02:21,390
- This one, right here?
- No!

50
00:02:21,391 --> 00:02:23,023
- Which one?
- The one behind you.

51
00:02:23,025 --> 00:02:24,225
- This one?
- Yes.

52
00:02:26,557 --> 00:02:27,657
[GROANS]

53
00:02:27,659 --> 00:02:30,693
[BOTH PANTING]

54
00:02:34,490 --> 00:02:35,525
He a relative?

55
00:02:36,225 --> 00:02:38,023
[LAUGHS]

56
00:02:38,025 --> 00:02:39,056
It's...

57
00:02:39,057 --> 00:02:40,359
It's a she.

58
00:02:40,757 --> 00:02:43,159
Are you sure that this...
[LAUGHS] that this is a she?

59
00:02:44,690 --> 00:02:47,092
[SNORTS]
That's Jenny's Aunt Winnie.

60
00:02:48,092 --> 00:02:51,659
It's actually a very
flattering portrait of her too.

61
00:02:54,225 --> 00:02:55,225
What...

62
00:02:59,859 --> 00:03:00,859
[SIGHS]

63
00:03:02,993 --> 00:03:04,092
Dell made a mess.

64
00:03:09,691 --> 00:03:10,726
I'm sorry.

65
00:03:12,690 --> 00:03:14,191
And I'm sorry I snapped at you.

66
00:03:15,190 --> 00:03:16,359
You didn't deserve that.

67
00:03:18,658 --> 00:03:21,092
Oh, it's... It's all right.

68
00:03:27,858 --> 00:03:29,191
Oh, shit.

69
00:03:30,359 --> 00:03:31,560
Are the guests still here?

70
00:03:35,725 --> 00:03:37,025
You ready to go party?

71
00:03:39,324 --> 00:03:40,324
[CHUFFS]

72
00:03:42,490 --> 00:03:43,592
I am if you are.

73
00:03:44,324 --> 00:03:47,159
[WOMAN SINGING OPERA]
```
if the user merge the subtitle before cutting the video then it cut the subtitle just fine.
this is not a new problem. was too lazy to open the issue thought someone would do it eventually no one did. 😓

it's an easily reproducible problem too.

**Comment by mifi** [comment] 2022-01-01 08:17
Thanks for reporting this! Actually, cutting and adding tracks from other files at the same time is not really something I've implemented support for yet. I think you will get the same problem if adding an audio track to a video and cutting segments at the same time, and I think the issue isn't related to subtitles only. So I consider this a feature request.

**Comment by mifi** [comment] 2022-01-15 10:25
actually I realised this is a duplicate of #896 - closing this. thanks anyways!

**Closed by mifi** 2022-01-15 10:25 UTC
Labels: enhancement

**Comment by Droyk** [comment] 2022-01-15 14:12
So someone did report it! should've checked it more carefully! anyway, any idea when it's gonna get implemented thanx!

**Comment by mifi** [comment] 2022-01-15 16:19
not sure yet, but leave a thumbs up on that issue. i will prioritise issues which are popular
