### ISSUE TITLE
cannot add audio track after discarding the previous one

### ISSUE THREAD

**Issue by gruianovac** [mifi/lossless-cut#1459] opened 2023-02-06 18:18 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

after discarding the audio of a file, i cannot add a new one.. i mean it shows as added, but it is not saved.  
note that i am not doing it in the same step ..

### Expected behavior

ideally should be done in the same step, but at least have it work sequentially

### Actual behavior

audio track not saved

**Comment by gruianovac** [comment] 2023-02-06 18:34
after restarting app switching from mp4 to mov worked. then tried mp4 worked also 

also why does adding a track is not actualized and be able to play.. you are forced to add, then export, then reimport..

**Comment by mifi** [comment] 2023-02-07 11:37
Duplicate of #976 - Losslesscut is not a non-linear editor. Please search and read docs before creating new issues.

**Closed by mifi** 2023-02-07 11:37 UTC
