### ISSUE TITLE
Audio failing to export

### ISSUE THREAD

**Issue by SaWools** [mifi/lossless-cut#1357] opened 2022-11-03 20:03 UTC
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

I would like to note that in the past, this worked fine, but today it refuses. I have rebooted my computer and switched to the newest version of lossless cut. The only other version I have used is 3.46.2

Add .m4a/mp3 file
Attempt to export, having touched nothing(from a fresh download of the zip folder and extracting)

### Expected behavior

A new file is exported

### Actual behavior

×
An error has occurred.
Cannot read property 'index' of undefined

### Share log

Before:
Version 3.47.1
main.ff7aecec.js:2 ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/static/js/main.ff7aecec.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/main.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/signals.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/core.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/realtime.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/cue.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/index.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/node.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/utf8.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/match.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/unicode.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/mbcs.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/sbcs.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/iso2022.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/command.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/cuesheet.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/static/css/main.6a515823.css.map

After:
Version 3.47.1
main.ff7aecec.js:2 ffmpeg -hide_banner -f lavfi -i 'nullsrc=s=256x256:d=1' -f null -
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/static/js/main.ff7aecec.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/main.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/signals.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/core.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/realtime.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/cue.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/index.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/node.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/utf8.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/match.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/unicode.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/mbcs.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/sbcs.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/iso2022.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/command.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/cuesheet.js.map
DevTools failed to parse SourceMap: file:///C:/Users/samaw/Downloads/LosslessCut-win-x64/resources/app.asar/build/static/css/main.6a515823.css.map
main.ff7aecec.js:2 userOpenFiles
main.ff7aecec.js:2 C:\Users\samaw\Downloads\Projekt Melody - Jonah reads a legendary Amazon review... [b_-C4iefXAQ].m4a
main.ff7aecec.js:2 loadMedia C:\Users\samaw\Downloads\Projekt Melody - Jonah reads a legendary Amazon review... [b_-C4iefXAQ].m4a undefined undefined
main.ff7aecec.js:2 state reset
main.ff7aecec.js:2 ffprobe -of json -show_chapters -show_format -show_entries stream -i 'C:\Users\samaw\Downloads\Projekt Melody - Jonah reads a legendary Amazon review... [b_-C4iefXAQ].m4a' -hide_banner
main.ff7aecec.js:2 formats mov,mp4,m4a,3gp,3g2,mj2
main.ff7aecec.js:2 fileType detected format {"ext":"mp4","mime":"video/mp4"}
main.ff7aecec.js:2 onDurationChange 1533.794104
main.ff7aecec.js:2 outSegTemplateOrDefault ${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}
main.ff7aecec.js:2 customTagsByFile {}
main.ff7aecec.js:2 customTagsByStreamId {}
main.ff7aecec.js:2 stdout: undefined
(anonymous) @ main.ff7aecec.js:2
async function (async)
(anonymous) @ main.ff7aecec.js:2
onClick @ main.ff7aecec.js:2
Ve @ main.ff7aecec.js:2
Ke @ main.ff7aecec.js:2
(anonymous) @ main.ff7aecec.js:2
Ar @ main.ff7aecec.js:2
Nr @ main.ff7aecec.js:2
(anonymous) @ main.ff7aecec.js:2
Le @ main.ff7aecec.js:2
(anonymous) @ main.ff7aecec.js:2
Mr @ main.ff7aecec.js:2
Jt @ main.ff7aecec.js:2
Zt @ main.ff7aecec.js:2
t.unstable_runWithPriority @ main.ff7aecec.js:2
qi @ main.ff7aecec.js:2
Pe @ main.ff7aecec.js:2
Qt @ main.ff7aecec.js:2
main.ff7aecec.js:2 stderr: undefined
(anonymous) @ main.ff7aecec.js:2
async function (async)
(anonymous) @ main.ff7aecec.js:2
onClick @ main.ff7aecec.js:2
Ve @ main.ff7aecec.js:2
Ke @ main.ff7aecec.js:2
(anonymous) @ main.ff7aecec.js:2
Ar @ main.ff7aecec.js:2
Nr @ main.ff7aecec.js:2
(anonymous) @ main.ff7aecec.js:2
Le @ main.ff7aecec.js:2
(anonymous) @ main.ff7aecec.js:2
Mr @ main.ff7aecec.js:2
Jt @ main.ff7aecec.js:2
Zt @ main.ff7aecec.js:2
t.unstable_runWithPriority @ main.ff7aecec.js:2
qi @ main.ff7aecec.js:2
Pe @ main.ff7aecec.js:2
Qt @ main.ff7aecec.js:2
main.ff7aecec.js:2 handleError TypeError: Cannot read property 'index' of undefined
    at o (main.ff7aecec.js:2)
    at Zb (main.ff7aecec.js:2)
    at main.ff7aecec.js:2
    at main.ff7aecec.js:2 undefined

**Comment by thekryz** [comment] 2022-11-04 10:40
Just tried to split an mp3, had the same issue. I'm on macOS Monterey. The MP3 was downloaded with yt-dlp as follows:
`yt-dlp -x --audio-format mp3 "4N_WD6Vkd9U"`

**Comment by SaWools** [comment] 2022-11-04 17:39
That worked for me too, but preview cannot include the second file in that version when combining audio and video. Will work until I figure out what the actual issue is.

**Comment by mifi** [comment] 2022-11-05 09:27
Hi. I think the problem is that you have "smart cut" enabled. Smart cut only works for videos, not audio. I will update the code so it doesn't crash but gives a proper error message instead.

**Comment by mifi** [comment] 2023-02-16 08:39
closing this ,as a believe it was fixed

**Closed by mifi** 2023-02-16 08:39 UTC
