### ISSUE TITLE
Play multiple audio tracks at once

### ISSUE THREAD

**Issue by Linnshet** [mifi/lossless-cut#936] opened 2021-11-25 15:08 UTC
LC has amazing potential for initial footage cutting, before the actual editing process. However, the inability to play multiple audio tracks at once is very limiting in this regard. 

Like a far view camera recording, with an external microphone track. If you can't hear what the person is saying, you have no chance of cutting it properly. And, as I imagine a lot of people who use the app use it for, Let's Play-content, where multiple audio tracks are mostly a given (one for gameplay, one for microphone, possibly even a third, fourth and fifth, in some cases).

At the moment, all I can really do is either:
1) play it in VLC with multitrack enabled, and cut based on timestamps (which I have to do manually, since I sadly haven't been able to find a "timestamp export" solution that works with LC.)
2) just skip this whole ordeal and boot up my actual editor.

I am absolutely certain that if this is not a technical limitation due to lack of caching ability, it will benefit a lot of users, and potential future ones as well.

**Comment by mifi** [comment] 2022-01-11 16:36
The problem is that the video player built into chromium doesn't even support switching between audio/video tracks to playback. So it needs to be implemented in a custom way. I have outlined some possibilities in #256
I will close this issue, because once we have implemented support for playing arbitrary audio and video tracks in the other issue, then playing multiple tracks at once shouldn't be very hard either. (added a point about that there)

**Closed as completed by mifi** 2022-01-11 16:36 UTC

**Comment by skelbread** [comment] 2023-02-21 04:04
> The problem is that the video player built into chromium doesn't even support switching between audio/video tracks to playback. So it needs to be implemented in a custom way. I have outlined some possibilities in #256 I will close this issue, because once we have implemented support for playing arbitrary audio and video tracks in the other issue, then playing multiple tracks at once shouldn't be very hard either. (added a point about that there)

1 year since, any update?

**Comment by mifi** [comment] 2023-02-23 06:58
yes! see #256 - chrome now suppotrs it. just need to implement

**Comment by fishheadcode** [comment] 2023-09-15 07:11
Hi, what is the status here? I want to cut my streams and i have like 5 tracks, mostly 3 are important (mic audio, desktop audio and seperate audio from discord). sometimes i want to cut by conversations, which would be 2 audio tracks but cant cut it that way or needed to always switch tracks, which is a very big time loss

**Comment by LukeHileman** [comment] 2023-09-17 01:13
also still waiting for this

**Comment by mifi** [comment] 2023-09-19 05:47
what are you all waiting for? being able to play multiple audio tracks **at the same time** (overlapping) or being able to switch between audio tracks when playing back?

**Comment by fishheadcode** [comment] 2023-09-19 06:26
waiting for that losslesscut **plays all audio tracks at the same time** so one can cut the clip hearing all audio. when game, mic and discord is 3 different audio tracks its difficult where to start and end. especially when you first "collect" clips from weeks and then want to "bulk edit" them.

**Comment by ehickey96** [comment] 2023-10-17 23:45
I am also looking for a way to manage clips with more than one audio track (and the tracks are intended to be played together). 
If lossless had a way to enable multiple specific or all tracks of audio during playback that would be amazing.

**Comment by N3X7L3VEL** [comment] 2023-11-09 18:07
Just commenting to keep me posted, I'd also love to see this feature up

**Comment by sardinhunt** [comment] 2024-06-16 00:57
I would love that too, do you guys know any alternatives I've been watching my clips on adobe audition, it's a pain.

**Comment by furbearingfish** [comment] 2024-07-02 12:07
Just chiming in to say I'd also love the ability to hear and edit both (or more) audio tracks at once. Love Lossless Cut, but this singular feature would make it much more handy.

**Comment by mifi** [comment] 2024-07-03 12:48
problem is I don't know how to do this easily with html video player. we're currently using the `audioTracks` api, however it doesn't seem to support enabling more than one at the same time.

**Comment by Nindroidica** [comment] 2024-12-16 23:04
Is this a thing yet? 

I've been using split audio tracks in the video file for recording gameplay audio, my mic, discord etc. via Steel Series GG + OBS. 

When recording in OBS I've been forced to create a duplicated audio track that combines all of those split audio tracks just for preview purposes in Lossless Cut and VLC media player that I delete when I video edit. 

The problem is when you use "re-play" background gameplay recorders like Metal TV and Steel Series GG that support multiple audio tracks you can only preview those audio tracks together in the software (or in a video editing software like davinchi resolve.) Also when you go to export, exporting the video combines the audio tracks into one and compresses the video, which I don't want and why I use lossless cut. 

If this ends up becoming an update it will save me so much hassle and headache.

**Comment by nohbodyyouknow** [comment] 2025-03-12 06:57
> I believe that chromium still doesn't support playing multiple tracks at the same time, so I'm not sure how to best implement it

very much looking forward to this, when it's possible (: this is the main feature keeping me from using it to trim down my terabytes of game clips to save space.

**Comment by mifi** [comment] 2025-03-14 05:20
next version will allow playing back multiple audio tracks simultaneously

**Comment by nohbodyyouknow** [comment] 2025-04-19 03:16
> next version will allow playing back multiple audio tracks simultaneously

this is huge! thank you so much for your hard work (:

**Comment by sardinhunt** [comment] 2025-05-02 11:05
> next version will allow playing back multiple audio tracks simultaneously

Nice, I got used having my first track as all tracks together because this wasn't there, lol ! I guess I have 3 tracks now and not 4. I'll donate losslesscut is a blessing

**Comment by sardinhunt** [comment] 2026-04-17 19:43
My opinion exactly
