### ISSUE TITLE
Allow importing Timestamps (CSV) too

### ISSUE THREAD

**Issue by mattack1** [mifi/lossless-cut#1221] opened 2022-07-08 23:45 UTC
Due to not having enough space to export the cut down file, I wanted to save the in/out points I had created for when I make space. (This was a many gig file downloaded from my Tivo.)

So I exported as Timestamps (CSV), but now realize that it doesn't support all of the formats for importing that it can export.

I manually recreated (approx) the same in/out points from the CSV file, and exported an LLC project that I can now import again... but it seems kind of confusing that it can't import all formats that it can export.

This is with the current version, 3.45.0.

**Comment by mifi** [comment] 2022-07-17 21:56
I would recommend using the default llc format for exporting/importing. but yea i agree it's nice if it can import more formats

**Comment by mattack1** [comment] 2022-07-18 16:44
Well, the reason I wrote this issue in the first place was because IMO it's VERY confusing to not be able to import at LEAST all of the formats it can export.  Especially when there are multiple import and export options, I had expected them to be paired.. and when they weren't, I basically lost data, since I had a 'meaningless' (for the current use case) timestamp file.

**Comment by mifi** [comment] 2022-07-20 10:10
closing as a dupe of #1176

**Closed by mifi** 2022-07-20 10:10 UTC
Labels: enhancement
