### ISSUE TITLE
allow synchronizing audio vs video tracks

### ISSUE THREAD

**Issue by KevinYork** [mifi/lossless-cut#2150] opened 2024-09-09 01:13 UTC
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

(In the past, I thought I saw a setting for this. But now that I need it; I don't see it)
allow synchronizing audio vs video tracks:

I am suggesting:
```
If you need to delay video by 3.84 seconds, use a command like this:
	ffmpeg -i "movie.mp4" -itsoffset 3.84 -i "movie.mp4" -map 1:v -map 0:a -c copy "movie-video-delayed.mp4"
If you need to delay audio by 3.84 seconds, use a command like this:
	ffmpeg -i "movie.mp4" -itsoffset 3.84 -i "movie.mp4" -map 0:v -map 1:a -c copy "movie-audio-delayed.mp4"
```

**Comment by mifi** [comment] 2024-09-12 02:01
I believe there was never a setting for this. I think duplicate of #216

**Closed by mifi** 2024-09-12 02:01 UTC
