### ISSUE TITLE
Request: Seek directly to keyframe

### ISSUE THREAD

**Issue by wave-dash** [mifi/lossless-cut#41] opened 2017-08-16 06:18 UTC
Thank you for making this program, it's a godsend when it comes to quick-and-dirty video cutting.

Being able to seek directly to a keyframe would make splitting videos much easier and faster. If the user so chooses, this would reduce the number of options you have to deal with.

For example, instead of wondering if you should cut at 10:01, 10:02, or 10:03, you could see that there's a keyframe at 10:02, making the decision pretty easy.

This could be implemented as GUI buttons similar to the seek forward/backward buttons, a keyboard shortcut (ctrl+right, ctrl+left), and/or clicking on the seekbar itself (ctrl click, for example).

**Comment by mifi** [comment] 2017-08-16 08:28
See discussion in #13. The problem is how to detect safe keyframes reliably and fast.

**Comment by mifi** [comment] 2017-10-21 17:33
I made a branch where I implemented this, however actually cutting on keyframe is not yet solved.
https://github.com/mifi/lossless-cut/tree/cut-on-keyframe

**Comment by wave-dash** [comment] 2017-11-13 06:21
Found myself using this again. I think some new commit might have broken cutting from 00.00.00.000, it's doing that frozen frame thing. Never ran into this issue before.

Possibly more related to this original topic, I also noticed that Lossless Cut's timestamps don't change with the framerate of the video. This shouldn't be a problem with video that's 60 FPS, or 30 or 15 or 10 etc, but it might not with frame rates that don't divide evenly. Most commonly would probably be 24 or 23.976 FPS. Potentially might even be affecting 59.94 FPS video.

**Comment by mifi** [comment] 2017-11-21 21:50
> Found myself using this again. I think some new commit might have broken cutting from 00.00.00.000, it's doing that frozen frame thing. Never ran into this issue before.

This is fixed in #50 

> Possibly more related to this original topic, I also noticed that Lossless Cut's timestamps don't change with the framerate of the video. This shouldn't be a problem with video that's 60 FPS, or 30 or 15 or 10 etc, but it might not with frame rates that don't divide evenly. Most commonly would probably be 24 or 23.976 FPS. Potentially might even be affecting 59.94 FPS video.

I don't quite understand this one.

> There are also some rare occasions where the timestamps seem to stop lining up with the video? For example, right now I'm looking at a seekbar that says 8.40.003. If I press comma to go back one frame, it says 8.39.987, seemingly skipping 8.40.000. After mess around with clicking the seekbar and skipping around by frame or by seconds, I can now get that same video to say 8.40.002.

The thing is that we are not aligning timestamps to frame timestamps at all, because the html5 video player does not expose this information. We could, however read frame timestamps using ffprobe or similar, but I don't think this gives us anything, unless we can tell ffmpeg to accurately cut on (key)frames

**Comment by mifi** [comment] 2020-02-22 15:55
Update: newest version shows keyframes on the timeline and lets you zoom in to accurately cut around keyframes. Next version I could let the user seek to keyframe.

**Comment by mifi** [comment] 2020-04-18 08:02
FYI Seek to keyframe is implemented with alt+left and alt+right. However don't expect ffmpeg to always cut at the keyframe selected. You may have to try "keyframe cut" or "normal cut" depending on codec and file.

**Closed by mifi** 2020-04-18 08:02 UTC
Labels: enhancement, keyframe-cut
