### ISSUE TITLE
v 3.45 - bugs

### ISSUE THREAD

**Issue by rubinrot59** [mifi/lossless-cut#1209] opened 2022-06-25 07:51 UTC
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
If neceeeessary i can made this sort of bug report, but I have not enough experience to do so. Sorry :((

**Describe the bug**
See the following chapter

**Expected behavior**
1. It's not possible to deactivate requesters (f.e. the window with the hint "Use the keyboard because the menu UNDO... doesn't work"). Expected: This feature should work (in version 3.44 this error window isn't available) 
2. The Year and the URL in the mp4-files of youtube clips getting always lost. Such files are playable also in apples software and software of other programmers. Expected: This feature should work (like in Version 3.44)  

**Screenshots**
Not necessary

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64bit, actual version level and actual patch level

**Additional context**
The version 3.44 worked better so I returned to this version.
Before I made the Bugreport I deleted all files in the AppData folder and in the registry of win. I'm using the portable Version which is delivered as a zip-file.

**Comment by mifi** [comment] 2022-06-26 23:44
> * It's not possible to deactivate requesters (f.e. the window with the hint "Use the keyboard because the menu UNDO... doesn't work"). Expected: This feature should work (in version 3.44 this error window isn't available)

duplicate of #1183

> 2\. The Year and the URL in the mp4-files of youtube clips getting always lost. Such files are playable also in apples software and software of other programmers. Expected: This feature should work (like in Version 3.44)

not sure what you mean, do you mean metadata? have you tried preserve all metadata (and mov metadata)?

**Comment by rubinrot59** [comment] 2022-06-28 08:33
Yes, the metadatas.
Youtube video contains very often the year of publishing and the URL of the video clip. In version 3.44 this feature worked proper, in 3.45 not.
As far as I know I had allowed in all preferences the meta data feature. Also the program is so adjusted that I have always the control about the outputs. I use the GUI expertmode also.

**Comment by mifi** [comment] 2022-06-29 23:43
do you have an example file (or youtube video + youtube-dl command to reproduce)?

**Comment by mifi** [comment] 2022-07-20 10:05
closing due to no response

**Closed by mifi** 2022-07-20 10:05 UTC
