### ISSUE TITLE
When I try to merge certain videos (all of them in the same codec) the result only shows the first video but when comes to the segment of the next files, it corrupts

### ISSUE THREAD

**Issue by Shideravan** [mifi/lossless-cut#945] opened 2021-12-03 11:56 UTC
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

Ok, I did everything described.

**Share information to help me understand**
- If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.
- If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)
- Please provide the error report if you got one (Menu: Help -> Report an error)

**Describe the bug**
Download the .zip with all the 3 videos I'm trying to merge here: https://drive.google.com/file/d/1u5KDFLziCNdjix6E9kztwEHqv2hq6OU_/view?usp=sharing
If I try to merge these 3 files, the final result has the full lenght, but only the first section are reproduciable. The video "hangs" after the segment from the first video.

**To Reproduce**
1. Open the 3 files in this zip "problematic files.zip"
2. Select to merge them, following the order ...PART1, ...PART2 and ...PART3
3. Wait until the file be created. Note that for this particular case, the percentage goest until 147% and not 100% in the lossless-cut
4. Execute the video. The video is corrupted after the first 8:24 (the length of the first video)

**Expected behavior**
It's expected for the merged file can be played from beggining to end.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Additional context**
Other similar videos I tried I had no issue. I also tried two different segments other than 3 of them. But the issue still happens.
Is something I'm doing wrong? Or is any kind of bug?

**Comment by mifi** [comment] 2022-01-11 14:26
Thanks for your thorough bug report! I downloaded your test files, and can confirm the issue. Even just merging PART1 and PART2 I see the same issue. Upon further inspecting the files, I see that part1 and part2 have differences in the audio codecs, so I believe this is causing the issue. See "Help -> Report an error" and inspect the audio track of each file. 

So I tried to remove the audio from each part separately, and then with the resulting (video only) files, I merged those, and it seems to be working nicely. Unfortunately there's not much to do about this other than you can possibly do this:
1. Extract the audio track for each part separately
2. use ffmpeg or some program to encode the audio files using aac (or FLAC) using the same codec parameters 
3. re-add the newly encoded audio tracks into the video parts, replacing the old audio tracks, then export each new part
4. now use the merge function on the new parts

Note this is not lossless for the audio, but the video is still lossless

**Comment by mifi** [comment] 2022-07-25 10:09
losslesscut will now warn if trying to merge different codecs. closing this

**Closed by mifi** 2022-07-25 10:09 UTC

**Comment by John-Development** [comment] 2025-05-10 23:29
Looks like still happens in some cases.
For instance, i am trying to add a fadeout to a video, so I cut the last seconds, reencode it using the same codecs, and when merging (no warnings) it corrupts ONLY if the reencoded video is placed second. It seems to work correcty if placed the first one... 

You can check it with the attached files (they are just the end part both reencoded and the original, because the first part was too long to attach):
if you merge them as "2-cut-s2 + 2-cut-s2_ffmpeg" it will corrupt, but if you revert the order it will work well.

[2-cut-s2.zip](https://github.com/user-attachments/files/20144298/2-cut-s2.zip)

**Comment by mifi** [comment] 2025-05-21 10:46
> if you merge them as "2-cut-s2 + 2-cut-s2_ffmpeg" it will corrupt, but if you revert the order it will work well.

I can reproduce the issue. Your issue might be a different one though, because your files have identical codec parameters ("check compatibility" gives no warnings).

I have no idea what's causing it, but most likely a bug or limitation in ffmpeg.
