### ISSUE TITLE
Failed to merge files with "..." (three dots) in the file name

### ISSUE THREAD

**Issue by misterpatate** [mifi/lossless-cut#934] opened 2021-11-25 07:13 UTC
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
When i try to merge multiple files which contain 3 dots in the filename with the Windows version of Lossless-cut I have a error message.

**Describe the bug**
error message when merging files with 3 dots in the filename.

**To Reproduce**
1. Open file 'My...Video.avi'
2. create at least 2 segments
2. Click on 'Export+merge'
3. See error (Unable to export this file)

**Expected behavior**
the software propose to rename file before merging.
or the software delete the dots in the filename before merging without prompt and re-add them in the final version.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Error: Command failed with exit code 1: G:\lossless-cut\resources\node_modules\ffmpeg-ffprobe-static\ffmpeg.exe -hide_banner -f concat -safe 0 -protocol_whitelist file,pipe -i - -c copy -map 0 -movflags +faststart -ignore_unknown -f webm -y E:\vimeo-download-master\MyVideo... test-cut-merged-1637823931919.webm
[concat @ 0000020ccafeee00] Impossible to open ' test-00.01.31.825-00.06.51.778-seg1.webm'
pipe:: No such file or directory
    at makeError (G:\lossless-cut\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (G:\lossless-cut\resources\app.asar\node_modules\execa\index.js:114:26)
    at async file:///G:/lossless-cut/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:66527
    at async file:///G:/lossless-cut/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:67099
    at async file:///G:/lossless-cut/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:192524
    at async file:///G:/lossless-cut/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:194036

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "E:\\vimeo-download-master\\MyVideo... test.webm",
    "fileFormat": "webm",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "vp9",
        "codec_long_name": "Google VP9",
        "profile": "Profile 0",
        "codec_type": "video",
        "codec_time_base": "1001/30000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": -99,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "refs": 1,
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "30000/1001",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "DURATION": "00:10:44.043000000"
        }
      },
      {
        "index": 1,
        "codec_name": "opus",
        "codec_long_name": "Opus (Opus Interactive Audio Codec)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": -7,
        "start_time": "-0.007000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "DURATION": "00:10:44.061000000"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "E:\\vimeo-download-master\\MyVideo... test.webm": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 91.82506666666667,
        "end": 411.7780333333333
      },
      {
        "start": 459.0586,
        "end": 583.7498333333333
      }
    ],
    "fileFormatData": {
      "filename": "E:\\vimeo-download-master\\MyVideo... test.webm",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "-0.007000",
      "duration": "644.061000",
      "size": "105360407",
      "bit_rate": "1308700",
      "probe_score": 100,
      "tags": {
        "ENCODER": "Lavf57.83.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.39.0"
}

**Comment by mifi** [comment] 2021-11-25 08:52
duplicate of #910 - will be released soon in a new version

**Closed by mifi** 2021-11-25 08:52 UTC
